### ISSUE TITLE
Feature request: weighted quantiles

### ISSUE THREAD

**Issue by floswald** [JuliaStats/StatsBase.jl#100]
something along the lines of R function Hmisc::wtd.quantile from the Hmisc package http://cran.r-project.org/web/packages/Hmisc/Hmisc.pdf would be useful.

```julia
quantile(x::Vector,w::WeightVec)
```

**Comment by ararslan** [comment]
#117 added the `wquantile` function and there is also a method now for `quantile` that accepts a `WeightVec`.
