### ISSUE TITLE
pacf() gives strange values

### ISSUE THREAD

**Issue by skeppet** [JuliaStats/StatsBase.jl#102]
When I use pacf() with method=:regression I get that it's almost zero for time lag 0. This should always be one, as far as I know.This does on the other hand not happen with method=:yulewalker. Am I the only one experiencing that?

If I compare the output of pacf(method=:yulewalker) with aryule() in MATLAB i get the same values but negative. Is there a good reason for that, or is it a bug?

**Comment by Nosferican** [comment]
Status of this?

**Comment by andreasnoack** [comment]
Looks like it was fixed in #309
