### ISSUE TITLE
Interface for histograms (AbstractHistogram)

### ISSUE THREAD

**Issue by jpata** [JuliaStats/StatsBase.jl#104]
This issue is meant to discuss the possibility of adding an `AbstractHistogram` interface which would allow methods of `Histogram` such as `push!` and `append!` be re-used. This would allow additional `*Histogram` types to be defined in a coherent way.

For a concrete case:
If one bins data with unequal weights and assumes the bin heights are sampled from independent Poisson distributions, the sum of weights squared for each bin is useful for keeping track of the estimated variance of the bin. This in turn can be used to tell whether two histograms are likely to arise from the same underlying distribution [1]. This would be a simple add-on for Histograms, see an example in https://github.com/jpata/HEP.jl/blob/master/src/hist.jl. This method is used heavily in high-energy physics experiments.

[1] http://arxiv.org/pdf/0712.4250.pdf

**Comment by simonbyrne** [comment]
Sorry it took me so long to merge, I must have missed it. Done now.
