### ISSUE TITLE
LoadError: @ngenerate

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/StatsBase.jl#106]
Latest Julia:

```julia
using StatsBase
```

>Warning: could not import Cartesian.@ngenerate into StatsBase
ERROR: LoadError: LoadError: UndefVarError: @ngenerate not defined
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading /home/julio/.julia/v0.4/StatsBase/src/weights.jl, in expression starting on line 158
while loading /home/julio/.julia/v0.4/StatsBase/src/StatsBase.jl, in expression starting on line 168

**Comment by toddleo** [comment]
I experience the same when building Julia with **userimg.jl**.

**Comment by andreasnoack** [comment]
cc: @lindahua

**Comment by tkelman** [comment]
This is now deprecated in Compat and giving warnings.
