### ISSUE TITLE
Warnings (conflict with existing identifier)

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/StatsBase.jl#109]
Latest Julia:

```julia
using StatsBase
```
>Warning: using StatsBase.midpoints in module Main conflicts with an existing identifier.
Warning: using StatsBase.histrange in module Main conflicts with an existing identifier.

**Comment by simonster** [comment]
I can't reproduce this. Did you load another package first?

**Comment by simonster** [comment]
Actually, it looks like this is a dup of #103, which indicates it only happens if you try to tab complete a name.

**Comment by juliohm** [comment]
@simonster, I can confirm, it only happens when I try to tab complete.
