### ISSUE TITLE
Error: Failed to get commit during Pkg.update()

### ISSUE THREAD

**Issue by sarvagnan** [JuliaStats/StatsBase.jl#110]
When running Pkg.update(), this error pops up,
ERROR: StatsBase: fetch failed to get commit e6411b644c, please file an issue at https://github.com/JuliaStats/StatsBase.jl/issues
 in error at error.jl:19
 in fetch at pkg/write.jl:19
 in update at pkg/write.jl:41
 in resolve at ./pkg/entry.jl:428
 in update at ./pkg/entry.jl:282
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:20
 in cd at pkg/dir.jl:28
 in update at ./pkg.jl:43

I've tried removing and reinstalling, all to no avail. How do I fix this?
Thanks!!!

**Comment by sarvagnan** [comment]
I received an additional error with another package, so i've deleted my .julia folder and this problem hasn't cropped up again yet.

**Comment by andreasnoack** [comment]
Unfortunately, this is (still) sometimes the easiest way to fix problems like this. Glad to hear that is solved the issue.
