### ISSUE TITLE
Entropy with different base

### ISSUE THREAD

**Issue by ahwillia** [JuliaStats/StatsBase.jl#127]
This is a really small point, but I think it would be nice to add a function that calculates entropy for any base:

```julia
function entropy{T<:Real}(p::AbstractArray{T}, b::Real) = entropy(p) / log(b)
```

The `Distributions` module already supports a [similar function](https://github.com/JuliaStats/Distributions.jl/blob/388eb766d509a168f9101980f5bd1695169b375d/src/multivariates.jl#L38).

Also, the [documentation for the `entropy` function](http://statsbasejl.readthedocs.org/en/latest/scalarstats.html#entropy) currently doesn't state what base is used for the logarithm.

Thoughts? I'm happy to open a pull request if others agree.

**Comment by simonbyrne** [comment]
This seems reasonable. We could also add a `entropy(d::Distribution,b::Real)` method to Distributions.jl as well.

**Comment by ahwillia** [comment]
Just opened a [PR](https://github.com/JuliaStats/StatsBase.jl/issues/127) that adds this for entropy, cross entropy, and KL divergence. Let me know your thoughts.

@simonbyrne -- the `entropy(d::Distribution,b::Real)` function actually already exists in Distributions.jl
