### ISSUE TITLE
mean(trim()) instead of trimmean(), to permit var(trim())

### ISSUE THREAD

**Issue by bjarthur** [JuliaStats/StatsBase.jl#132]
given that one might want to compute other statistics, besides just the mean, on trimmed data (e.g. the variance), would it make sense to provide, instead of trimmean(), a function, which could be called trim(), that just trimmed the input for the user to then do what they wanted?

relatedly, a close alternative to trimmed estimators are those that are winsorized--  where, instead of removing the extreme values, they are clamped.  i would find it useful if StatsBase.jl provided a winsor() function similar to the proposed trim() above.

i have code to do both, and could submit a PR.

**Comment by nalimilan** [comment]
That's an interesting design issue. To make `mean(trim())` be efficient, it would be necessary to avoid making a copy of the data when calling `trim()`. In other words, `trim()` would have to return a special view of the original data, which would skip trimmed values. It would probably be easy to return `NaN` for those values, which would allow indexing that object using the indexes from the original data, making it completely array-like. Same strategy for `winsor()`.

Now, is that really useful? How many functions would be used in combination with `trim`? Wouldn't it be simpler to add a `trim` argument to them?

**Comment by dcarrera** [comment]
I personally wouldn't use a `trim()` but I would use a `winsor()` because you can use the Winsorized variance to get the variance of the trimmed mean. Wilcox (2010) gives the following formula:

```
   Variance of trimmean(xs,p)  =  var(winsor(xs, p)) / ( (1 - p) * length(xs) )
```

**Comment by nalimilan** [comment]
Thanks to @dcarrera and @bjarthur we now have generic `trim` and `winsor` functions returning modified copies of the input vector, and `trimvar` to compute the variance of the trimmed mean.

As a further improvement, it would be interesting to have non-copying functions for these features. They could return a special iterator which would skip/replace extreme elements. This should be significantly faster for operations like computing the trimmed mean, where you discard the trimmed vector immediately.
