### ISSUE TITLE
A Ones type

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/StatsBase.jl#135]
A Ones type would be something like

``` julia
immutable Ones{N} <: AbstractArray{Int,N}
    dims::NTuple{N, Int}
end
Base.size(O::Ones) = O.dims
Base.getindex(O::Ones, I::Int...) = (checkbounds(O, I...); 1)
```

(see [this stackoverflow answer](http://stackoverflow.com/a/30968709/3662288) for the original proposal by @mbauman).

It's helpful because it allows to write efficient, generic code:
- Its default behavior matches a vector of ones, without the memory allocation
- Frequently,  a non weighted operation can be written more efficiently than the weighted case with a vector of ones. Defining a neutral weight type such as Ones allows to branch elegantly between the weighted and the non weighted versions.

It's a good application of multiple dispatch. It would be great to define something like this in StatsBase.

**Comment by matthieugomez** [comment]
Why should such a type be defined in `StatsBase`? 
Suppose I need to compute the median within a function that may or may not be passed weights. For efficiency, I need to call `median(x)` in the no weight case vs `median(x, w)` in the weight case. I'm not sure how to do that in a elegant way. In contrast, if  `median(x, w::Ones) = x` is defined in `StatsBase` defined, I just need to write `median(x, w)` to handle either case. In effect, dispatch on the number of argument is replaced by a type dispatch. 
Even better, suppose I actually did not know that `median` was more efficient than the unweighted case. I would still write `median(x, Ones(length(x)))` to avoid the allocation of a weight vector (back to the first point). But now, the definition in `StatsBase` automatically dispatches to the efficient method when `w` is of type `Ones`

**Comment by johnmyleswhite** [comment]
I think this is pretty reasonable and a potentially good change, but it adds more complexity.

I would like us to improve the design of our weighting functionality at some point to handle weights with different interpretations (right now everything is a frequency weight); maybe we can address this concern then?

We probably need a different name than `Ones`, which is too vague. Something like `UniformWeights` would be better.

**Comment by nalimilan** [comment]
`UnitWeights` might be even better. In the literature, uniform weights sometimes mean `1/N`, `N` being the number of cases. Unit weights doesn't have that ambiguity.

**Comment by matthieugomez** [comment]
Great! I'm also a supporter of different kinds of weights.

**Comment by sbromberger** [comment]
Hi,

I may have implemented something like this in LightGraphs: see https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/distance.jl#L5-L9). Let me know if it's useful.

**Comment by nalimilan** [comment]
I've just realized it might be possible to implement this using `repeated()` from Julia Base. See https://github.com/JuliaLang/julia/pull/15988.

**Comment by Nosferican** [comment]
Any updates in implementing `UnitWeights`?

**Comment by nalimilan** [comment]
Do you want to give it a try? It shouldn't be hard to do (most of the work should be adapting tests to cover it).

**Comment by Nosferican** [comment]
Sure. I will see if I can give it a try in the next few days and get a PR to review.

**Comment by Nosferican** [comment]
`FillArrays.Ones`
