### ISSUE TITLE
Quantile location

### ISSUE THREAD

**Issue by iceblue25** [JuliaStats/StatsBase.jl#145]
Hi and thanks for the wonderful package. Quantile (median etc) functions return the ranked statistics. Is there a way to get the location of the value also? Quantile does not seem to return that.

Thanks

**Comment by nalimilan** [comment]
Do you mean the index of the entry corresponding to the quantile? This can't work in general, as several values, or none, can be equal to the returned quantile. Only for sorted vectors a kind of meaningful index could be returned.

BTW, please use the mailing list for questions.

**Comment by iceblue25** [comment]
Thanks I mean the index of the corresponding quantile as an array or the first occurrence or something.

Where is the mailing list?

**Comment by nalimilan** [comment]
See https://groups.google.com/forum/#!topic/julia-stats/

If you want the first occurrence, you can just find it easily e.g. using `findfirst`. I don't really see the point of adding a new function for something that isn't so well-specified.

**Comment by iceblue25** [comment]
The link does not exist for me. 

The first reason is efficiency since quantiles are computed anyway and the function knows the location, it just doesnt return. 

Also, if the number to match is a float sometimes it just doesnt exactly match due to internal rounding errors and exact match of floats (If find matching exact floats problematic in many applications). I will have to search for value-error<= x <= value+error

Thanks

**Comment by johnmyleswhite** [comment]
Closing as too vague to be actionable.

**Comment by nalimilan** [comment]
@iceblue25 I think if you look at a possible implementation, you'll see that it doesn't make sense except in very specific cases. You'd better write your own custom function.
