### ISSUE TITLE
autocor Why 100 elemnts vector has not 100 elements autocor output ?

### ISSUE THREAD

**Issue by paulanalyst** [JuliaStats/StatsBase.jl#147]
Why 100 elemnts vector has not 100 elements autocor output ?
julia> autocor(rand(10))
10-element Array{Float64,1}:
  1.0
  0.363742
 -0.11318
 -0.222987
  0.0235896
  0.0205071
 -0.135124
 -0.242747
 -0.140223
 -0.0535775

julia> autocor(rand(100))
21-element Array{Float64,1}:
  1.0
  0.0187758
 -0.105103
 -0.0232407
  0.0636284
  0.0438567
 -0.246789
 -0.00484981
  0.00894277
 -0.0909333
 -0.00114724
  0.142196
  0.0421625
  0.0117317
  0.109289
  0.122338
 -0.0507566
 -0.114893
  0.130828
 -0.0543573
 -0.0132691

**Comment by johnmyleswhite** [comment]
Please don't ask elementary usage questions on GitHub.

**Comment by karlwessel** [comment]
I was surprised by this behaviour as well because the docs for `autocor` say that 
`If x is a vector, return a vector of the same length as x.`

Can that part of doc just be removed? (could do that as a PR in that case)

**Comment by nalimilan** [comment]
@karlwessel Yes, please do (rather than removing, if you can explain what happens it's even better).

**Comment by karlwessel** [comment]
Thanks to @fzierler for fixing this! Sorry I didn't get to do it as promised... :(
