### ISSUE TITLE
Covariance on train.csv

### ISSUE THREAD

**Issue by hpoit** [JuliaStats/StatsBase.jl#157]
How do I run `cov(X, wv[; vardim=1, mean=nothing])` on 

train.csv from https://s3-sa-east-1.amazonaws.com/nu-static/workable-data-science/puzzle.html?

**Comment by johnmyleswhite** [comment]
This kind of usage question should go to julia-users. We like to keep this issue tracker focused on core problems that developers need to address. This kind of usage question is better suited for a more diverse audience and a less focused forum.

**Comment by StefanKarpinski** [comment]
Maybe [julia-stats](https://groups.google.com/forum/#!forum/julia-stats)?

**Comment by hpoit** [comment]
Posted there, let's see what happens.
