### ISSUE TITLE
Support multi-dimensional arrays in `sample`

### ISSUE THREAD

**Issue by abbradar** [JuliaStats/StatsBase.jl#161]
Ditto title. I imagine this as adding a new `dim=` optional argument to `sample` which allows to specify dimension across which sampling needs to be done. This would allow us, e.g., to sample `DataFrame`s.

EDIT: as a bonus, it would be nice to support working on several arrays simultaneously, specifying dimension for each one (assuming that they are same-sized on that dimension).

**Comment by ararslan** [comment]
Looks like there already is a method for `sample` that takes a dimension. See https://github.com/JuliaStats/StatsBase.jl/blob/master/src/sampling.jl#L323. Is that what you're after?

**Comment by amrods** [comment]
`sample` does not dispatch method 8 of the methods table:
```
sample(a::AbstractArray, dims::Tuple{Vararg{Int64,N}} where N; replace, ordered)
```

so `sample(1:100, (2,2))` gives a methods error:
```
julia> sample(1:100, (2,2))
ERROR: MethodError: no method matching sample!(::MersenneTwister, ::UnitRange{Int64}, ::Array{Int64,2}, ::MersenneTwister; replace=true, ordered=false)
```

I think this is because the rng argument is repeated in line 393 of sampling.jl

**Comment by amrods** [comment]
Should this issue be closed?
