### ISSUE TITLE
Quantile output not sorted

### ISSUE THREAD

**Issue by cstjean** [JuliaStats/StatsBase.jl#164]
On Julia 0.4.5 and the latest release of StatsBase:

```julia
y = [0.40003674665581906,0.4085630862624367,0.41662034698690303,0.41662034698690303,0.42189053966652057,0.42189053966652057,0.42553514344518345,0.43985732442991354]
issorted(quantile(y, linspace(0.01, 0.99, 17)))   # false
```

The quantiles are:

```
[0.4006335904282823,0.4042892585346196,0.40794492664095694,
0.4114334853955278,0.41488803593114276,
0.41662034698690303,0.416620346986903, # these two not in order
0.4169958482153258,0.41925544332671183,0.4215150384380978,0.42189053966652057,
0.42189053966652057,0.4226741294789331,0.42423675334903477,0.42657350156657636,
0.4327141366637794,0.4388547717609824]
```

Is that a bug, or is it a conscious decision to define "empty quantiles"?

**Comment by andreasnoack** [comment]
The difference is smaller than `eps()` and you are asking for more quantiles than you have data points. Is this a real problem for you?

**Comment by simonbyrne** [comment]
This is actually a problem in Base, particularly [this line](https://github.com/JuliaLang/julia/blob/21a7d4d93896cfbc4b6c887ec35f0f03dbddb61a/base/statistics.jl#L592).

I think we can fix this by changing

    (1-h)*T(v[i]) + h*T(v[i+1])

to

    T(v[i]) + h*(T(v[i+1])-T(v[i]))

**Comment by cstjean** [comment]
It's not a problem for my algorithm, but FWIW it originally happened on a dataset with more unique values than quantiles. I just trimmed it to file the issue.

**Comment by cstjean** [comment]
Thank you for the quick fix @simonbyrne and @andreasnoack
