### ISSUE TITLE
ecdf function

### ISSUE THREAD

**Issue by rand5** [JuliaStats/StatsBase.jl#165]
I am having trouble with the ecdf function. Whenever I try to call it, via something like, 
`StatsBase.ecdf(rand(100))`
I get the following result:
`ef (generic function with 2 methods)`

Just updated my packages and no change. 
Any help is appreciated.
Thanks,

**Comment by johnmyleswhite** [comment]
That's the correct result. You call that function to evaluate the ECDF at an arbitrary point.

For future reference, this kind of usage question is better suited for julia-users.

**Comment by ptoche** [comment]
I understand the question, but not the answer...

**Comment by ararslan** [comment]
> That's the correct result. You call that function to evaluate the ECDF at an arbitrary point.

The behavior noted in the question, that the `ecdf` function returns a function, is expected. The returned function is used to evaluated the ECDF computed from the input to `ecdf`.

> For future reference, this kind of usage question is better suited for julia-users.

julia-users is a now-defunct mailing list for Julia usage questions. Such questions should now be posted to [Discourse](https://discourse.julialang.org) instead.

**Comment by ptoche** [comment]
Thanks Alex. I was looking for a link to Discourse, but I did not remember the name and was looking around the github interface for it. A link to this in the [readme](https://github.com/JuliaStats/StatsBase.jl) would be useful. And a sticky post at the top of issues to redirect to Discourse, if feasible.

**Comment by sarah-ji** [comment]
I am also having this issue. I have an Array{Float64,1} that ranges from 0 to 0.5 named 'maf', that I would like to calculate the empirical cdf for to map the corresponding values in the array to values between 0 and 1. 

After running ecdf(maf) I got the same result ef (generic function with 2 methods)

then following the instructions above, I tried doing ef(0.5) to see if I would get 1 (as the max is 0.5), but  instead I get an error that reads: UndefVarError: ef not defined

What do you mean by "calling/using the function" above? Can anyone help clarify?

**Comment by ararslan** [comment]
```
julia> x = randn(100);

julia> f = ecdf(x)
(::getfield(StatsBase, Symbol("#ef#91")){Float64,Array{Float64,1},Int64}) (generic function with 2 methods)

julia> f(0.5)
0.73
```

**Comment by sarah-ji** [comment]
Wow! Thank you so much @ararslan 💃
