### ISSUE TITLE
Naming of AIC, BIC, and AICc

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/StatsBase.jl#177]
The function names `AIC`, `BIC`, and `AICc` are presumably in all caps for similarity with how one would write them outside of code. However, it's a little confusing because folks familiar with Julia naming conventions might assume that these are types rather than functions, since types are typically in upper camel case and functions in lowercase.

Thus, I propose that `AIC`, `BIC`, and `AICc` be deprecated in favor of `aic`, `bic`, and `aicc`. If people think this is a good idea I'd be happy to submit a PR.

**Comment by nalimilan** [comment]
That's a tough call. I find acronyms much clearer in capitals. But it's true that the style guide says function names should be in lower case: http://julia.readthedocs.io/en/latest/manual/style-guide/#use-naming-conventions-consistent-with-julia-s-base. I guess we should proceed with the deprecation, but we could ask for opinions on the mailing lists, and make the rule very clear in the style guide.

**Comment by ararslan** [comment]
Sounds good to me.

**Comment by ararslan** [comment]
> I find acronyms much clearer in capitals.

Come to think of it, naming `AIC` et al. as such is actually inconsistent with other functions in the package. For example, `pacf` is an acronym (for "partial autocorrelation function") and is in all lowercase.
