### ISSUE TITLE
Add dimension specification for mode()

### ISSUE THREAD

**Issue by matago** [JuliaStats/StatsBase.jl#181]
I am wondering if it would be possible to implement dimension specification for `mode()` in a similar fashion to `mean()` and `sum()`.  `mode(A,1)` would provide column modes and `mode(A,2)` row modes across Array `A`

**Comment by nalimilan** [comment]
Shouldn't be too hard, but I wonder whether we should go into that direction: then we'll eventually have to implement this for all reductions. Maybe we should keep this limited to `sum` and `mean`, and use `reducedim(f, A, dims)` for other operations?

**Comment by nilshg** [comment]
Would this be covered by https://github.com/JuliaStats/StatsBase.jl/issues/77 and thus the fact that we now have `eachslice`?
