### ISSUE TITLE
Change default for "closed" argument for histograms from right to left

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/StatsBase.jl#184]
Currently, histogram ranges are closed-right be default. I would argue that in the vast majority of real-life use cases, this is not what the user wants: One deals with positive-only data far more frequently than with negative-only data, and 0.0 frequently _does_ occur in real-life data. A few examples:
- Things like `a * rand()` yield values from the interval [0, a[, not ]0, a]:
  
  ```
  rand(r::AbstractRNG) = rand(r, CloseOpen)
  ```
- Instruments that measure positive quantities often output 0.0, if the input is below their resolution.
- In data analysis, when histogramming derived positive quantities (e.g. peak heights), 0.0 also often occurs when dealing with finite-resolution data (e.g. from an ADC that will output 0,1,2, ...).
- ...

It's cumbersome (and easy to forget) to always add `closed = :left`, and I fear that it will result in people overlooking the fact that their data contains zeros (I've seen many students make that mistake in general ...).

I realize that Base.hist uses closed-right intervals as well - and I think we should change that, too.

**Comment by nalimilan** [comment]
The default is the same in R, so there might be a reason for it. Though in R `include.lowest=TRUE` by default, which means it works fine for positive-only data. Maybe we should add that argument?

FWIW: `hist` has been deprecated in Julia 0.5, the one in StatsBase should be used instead (and is thus the only one to fix).

**Comment by oschulz** [comment]
Well, I don't think we need to be slaves to R. ;-) 

PyPlot histograms, for example, certainly include 0 on the left:

![pyplot-hist-closed-left](https://cloud.githubusercontent.com/assets/546147/16616127/7571285e-437b-11e6-9759-25f3f3ffdd0a.png)

So do other important data analysis frameworks, like [ROOT](http://root.cern.ch).

Also, it seems unlogical that Julia's default for random number generation should be CloseOpen, but the exact opposite for it's central statistics package.

**Comment by simonbyrne** [comment]
Not sure what the best option is, but for some background, see https://github.com/JuliaLang/julia/pull/6601#issuecomment-41148848.

**Comment by nalimilan** [comment]
Note I said "there might be a reason", but there might not. Indeed, the fact that other programs use a different default is an interesting point.

Actually, in the thread Simon linked to, I had said that I'd prefer closed on the left. I think I'd still be in favor of that, since the historical reasons related to float ranges no longer apply.

**Comment by oschulz** [comment]
@nalimilan: Sure, I didn't want to imply anything (and I didn't know about the history). Certainly if R does things in a specific way, there may be a very good reason for it, and R's reasons should certainly be taken into consideration. I just wanted to show that some other serious projects default to closed-left.

I guess in the end, people will do a histogram over, e.g. `0:0.1:10` far more frequently than one over `-10:0.1:0`, and they will (usually) not want to leave 0.0 out. Also since, in general, 0 is more often lumped in with the positive, rather than the negative numbers, I think that also for a histogram over, say -4:0.1:4, people will intuitively expect to find the 0.0 values in the first positive bin.

The most important point to me is that the dynamic range of real-life data, at least in my personal experience, is almost always closed-left: If you set an instrument to input range X, that usually means [0, X[. But as mentioned above, it's usually true for generated data, like random numbers, as well).

If the historical reasons historical for choosing closed-right now longer applies, maybe a change could be considered at this point?

**Comment by oschulz** [comment]
Sure, iI'll make a PR. I also like the idea of being able to close on both sides - I guess that would mean `closed = :left, :right, :both`?

**Comment by oschulz** [comment]
> Sure, I'll make a PR. I also like the idea of being able to close on both sides - I guess that would mean closed = :left, :right, :both?

On second thought, maybe `closed = :left | :right | :both` is not a good idea, because we couldn't select where to put in 0.0 for -4:0.1:4 any longer. So an additional boolean argument `include_extrema = true | false`?

**Comment by nalimilan** [comment]
> So an additional boolean argument include_extrema = true | false?

Yes, and that's a better name than `include.lowest`.

**Comment by simonbyrne** [comment]
As I suggested on the other thread, we could use `RoundDown`, `RoundUp` here, thought that might be too confusing.

**Comment by nalimilan** [comment]
@simonbyrne I'm not sure the analogy is really obvious here. Speaking in terms of open/closed intervals sound more standard to me.

**Comment by oschulz** [comment]
The PR for changing the default to close-left is ready: #185

Concerning a `include_extrema` option, I have a feeling that requires a bit of thought, especially when it comes to integer data, so I think this should be a separate issue.

**Comment by oschulz** [comment]
I guess we can close this now.
