### ISSUE TITLE
StatsBase requires StatsFuns 0.3.0, which does not exist for Julia 0.4

### ISSUE THREAD

**Issue by richardreeve** [JuliaStats/StatsBase.jl#192]
The REQUIRE statement in StatsBase is currently unsatisfiable for Julia 0.4 as StatsFuns 0.3.0 requires Julia 0.5.

**Comment by ararslan** [comment]
Unfortunately this is a known issue. Fixing StatsFuns to accomodate Julia 0.5's removal of Rmath lit the entire JuliaStats world on fire. 🔥🔥🔥 A few of us are working on getting this fixed ASAP. 🚒

**Comment by richardreeve** [comment]
Sorry to hear that...

**Comment by ararslan** [comment]
I'm sorry for the inconvenience!

**Comment by richardreeve** [comment]
I'm sure trying to get everything ready for Julia 0.5 is not easy.

**Comment by ararslan** [comment]
This should be fixed now. Let me know if you run into any more issues.
