### ISSUE TITLE
Where did rand_binom go?

### ISSUE THREAD

**Issue by Ward9250** [JuliaStats/StatsBase.jl#194]
Hi,

Some modules in Bio.jl depend on LightGraphs which explicitly imports rand_binom from this package, but recently that's been resulting in an undefvar error. Where is rand_binom functionality now?

Thanks,
Ben.

**Comment by andreasnoack** [comment]
Please use `Distributions`' `rand(Binomail(n,p))` for this. There is still `StatsBase.binomrand` but eventually it will be removed in favor of `Distributions`.

**Comment by Ward9250** [comment]
Thanks @andreasnoack, I shall pass on the info :)

**Comment by ararslan** [comment]
The only reason `binomrand` is available from StatsBase currently is that it's being explicitly imported from StatsFuns. Using `StatsBase.binomrand` directly is probably not what you want anyway because it returns a float rather than an int, whereas `rand_binom` returned an int.
