### ISSUE TITLE
Changed meaning of .+= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [JuliaStats/StatsBase.jl#195]
Your code uses `x .+= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x .+ y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `.+` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

At first glance, this looks like it is okay for you, because you use it in `widths .+= 1`, where it looks like you want to work in-place anyway?  But if it were a problem you could always change it to `+=`.

**Comment by ararslan** [comment]
Thanks for the heads up. Looks like things are and have been working, so I think we're all good here.
