### ISSUE TITLE
outlier fences

### ISSUE THREAD

**Issue by bjarthur** [JuliaStats/StatsBase.jl#205]
i don't see a means to determine outliers anywhere in JuliaStats.  i'd be happy to submit a PR for the code below if people thought it useful. 

```
function outlier_fences(data)
  q1,q3 = quantile(data,[0.25,0.75])
  iqr = q3-q1
  minor = 1.5*iqr
  major = 3*iqr
  q1-major, q1-minor, q3+minor, q3+major
end
```

**Comment by nalimilan** [comment]
Not sure, but thanks for the proposal. Do other statistical packages offer such a function?

**Comment by ararslan** [comment]
I don't think I've seen such a function in other statistical packages, but some plotting methods in R identify and mark outliers. One example is in box plots, where outliers appear as separate points beyond the whiskers. I don't know how useful such a function would be on its own here, but maybe this would be a good fit in StatPlots.jl?

**Comment by bjarthur** [comment]
determining outliers is useful for more than just making plots.  say for example you want to fit a line but don't want to include the outliers because they would perturb the result.

thinking on this more, since there a large number of ways to test for outliers, this being just one, long term it might make sense to have a separate package for them in JuliaStats, say OutlierDetection.jl.

**Comment by nalimilan** [comment]
That's why I wondered how other software handles this.

**Comment by ararslan** [comment]
A separate package with a variety of ways to detect outliers sounds like a good idea to me.

**Comment by bjarthur** [comment]
https://github.com/bjarthur/Outliers.jl
