### ISSUE TITLE
migrate `cov` and friends from `Base` to `StatsBase`

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/StatsBase.jl#207]
In the discussion of [Julia issue #4113](https://github.com/JuliaLang/julia/issues/4113#issuecomment-241189020), it was suggested that `cov` and related functions should be migrated out of Julia `Base`. I am opening this issue to initiate discussion. If the maintainers are receptive, I would be happy to do a PR.

**Comment by nalimilan** [comment]
+1

While you're at it, I'd even move `cor` and `std`, so that it's clear all statistical functions live in StatsBase.

**Comment by nalimilan** [comment]
@StefanKarpinski Opinions on this (see @andreasnoack's reaction on the linked thread)?

**Comment by nalimilan** [comment]
These functions will continue to live in Statistics, and we'll probably move more functions there in the future.
