### ISSUE TITLE
Both StatsBase and DataArrays export some functions

### ISSUE THREAD

**Issue by ranjanan** [JuliaStats/StatsBase.jl#208]
I got this on using DataFrames 0.7.8: 
```
julia> a = roadWARNING: both DataArrays and StatsBase export "autocor"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "inverse_rle"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "rle"; uses of it in module DataFrames must be qualified
```

**Comment by ararslan** [comment]
Both DataFrames and DataArrays do `@reexport using StatsBase`. I assume that's what's causing the issue. I'm not super familiar with `@reexport` though, so maybe that's not accurate.

**Comment by nalimilan** [comment]
Looks like a more general issue, as it's quite common for two packages to extend a third package's functions.

@simonster Is Reexport.jl supposed to work in that case?

**Comment by simonster** [comment]
Reexport is just syntactic sugar for `export`, but it looks like DataArrays might be defining its own copies of these functions rather than extending the functions from StatsBase, e.g. [here](https://github.com/JuliaStats/DataArrays.jl/blob/af1f8da6d28959bc9125c2cc062f859af15e22c2/src/operators.jl#L872).

**Comment by nalimilan** [comment]
Ugh, DataArrays really includes too many functions. We should definitely remove these generic definitions and import those from StatsBase.

**Comment by andreasnoack** [comment]
> We should definitely remove these generic definitions and import those from StatsBase.

This is very much the idea behind `StatsBase` so this issue should be moved to`DataArrays`.

**Comment by ararslan** [comment]
I'm going to go ahead and close this since, as Andreas said, this should be discussed as a modification to DataArrays.jl.
