### ISSUE TITLE
Better name for df?

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/StatsBase.jl#216]
@nalimilan pointed out recently that `df` has an unfortunate name conflict with the abbreviation for `DataFrame`. (It also conflicts with R's _F_ density function, which may be confusing for newer users.) So while "df" is a commonly used abbreviation for "degrees of freedom" in statistical literature, I think it would be worth having a more descriptive name for the function here.

So if other folks think this is a good idea, let the name bikeshedding begin!

**Comment by ararslan** [comment]
A couple of possibilities to start us off: `dof`, `degf` (as suggested by Milan), `degfree`

**Comment by ChrisRackauckas** [comment]
`dof` makes a lot of sense to me. I've see it abbreviated like that in textbooks before.

**Comment by ViralBShah** [comment]
I routinely use `df` for dataframe. `dof` sounds like the way to go.

**Comment by nalimilan** [comment]
Indeed I had proposed `degf`, but `dof` sounds more common. (I liked `df`, though, and another solution would be to stop using that name for data frames. :-)

**Comment by ararslan** [comment]
> another solution would be to stop using that name for data frames.

Easier said than done 😉

**Comment by ararslan** [comment]
Since `dof` is the clear frontrunner, I've opened a PR to use `dof`. However, I'd still be interested to hear from others regarding this issue. If consensus changes I can adjust the PR accordingly.

**Comment by kmsquire** [comment]
+1 for `dof`

**Comment by ViralBShah** [comment]
I think in general, we should avoid using 2 and 3 letter names. `dof` seems to work perfectly here, though.

**Comment by ararslan** [comment]
Since there's unanimous support for `dof`, I'll go ahead and merge the PR. Thanks everyone!
