### ISSUE TITLE
Problem of fit(Histogram... with UInt

### ISSUE THREAD

**Issue by andferrari** [JuliaStats/StatsBase.jl#220]
When computed on UInt `fit(Histogram..` seems to ignore half of the range. 
E.g.

``` julia
using StatsBase
x = convert(Array{UInt8,1},[10, 127, 127, 128, 152])
h = fit(Histogram, x, 0:256).weights
find(h.>=1)
```

returns `10` and `127`

**Comment by simonbyrne** [comment]
Issue in Base https://github.com/JuliaLang/julia/issues/19005

**Comment by simonbyrne** [comment]
Issue is now fixed in Base.
