### ISSUE TITLE
New zero(::Any) test failure on Julia 0.4

### ISSUE THREAD

**Issue by tkelman** [JuliaStats/StatsBase.jl#221]
I don't think this was tagged yesterday, so http://pkg.julialang.org/logs/StatsBase_0.4.log is a bit surprising. Did a test dependency get tagged and break something, or is it intermittent?

**Comment by ararslan** [comment]
Hm, that's the first time I've seen that.

**Comment by andreasnoack** [comment]
It's because `@compat .foo` is generating `Any` arrays on 0.4 and https://github.com/JuliaLang/julia/blob/release-0.4/base/test.jl#L121 assumes a tighter type bound on the array. Fix incoming.

**Comment by nalimilan** [comment]
Cool. But how is it possible that it didn't show up before?

**Comment by andreasnoack** [comment]
Not sure why. The actual change was in GLM but it doesn't seem recent. The tagging of `GLM.jl` has gone wrong. See https://github.com/JuliaStats/GLM.jl/releases but I don't know if that could have an effect. @ararslan Do you know what has happened?

**Comment by tkelman** [comment]
that's not wrong. https://github.com/JuliaStats/GLM.jl/issues/159

**Comment by andreasnoack** [comment]
I see. Thanks.

**Comment by andreasnoack** [comment]
Then the reason is that https://github.com/JuliaStats/GLM.jl/releases/tag/v0.5.6 is the first release tested against a version of GLM with `https://github.com/JuliaStats/GLM.jl/commit/e6eaf0e57b5079c87014129cb2c7054d46723047` on 0.4.

**Comment by tkelman** [comment]
I think that commit was also included in 0.5.5

**Comment by ararslan** [comment]
Tony's right, that's also in 0.5.5.

**Comment by ararslan** [comment]
Looks like Andreas fixed this in #222.
