### ISSUE TITLE
Histogram, normalized to area 1

### ISSUE THREAD

**Issue by alanedelman** [JuliaStats/StatsBase.jl#231]
I don't think I see an empirical pdf or a histogram normalized so that the area
is 1 ?

**Comment by andreasnoack** [comment]
I don't we support this right now. See also https://github.com/JuliaStats/KernelDensity.jl

Cc: @simonbyrne.

**Comment by alanedelman** [comment]
Unexcusable  :-)
Hope this can be added asap.

**Comment by oschulz** [comment]
I have code ready for this - I'll put a PR together.

**Comment by oschulz** [comment]
See PR #242.

**Comment by oschulz** [comment]
See PR #243.

**Comment by alanedelman** [comment]
thanks

**Comment by andreasnoack** [comment]
Fixed by #243

**Comment by avigliotti** [comment]
Hi,

I am running julia1.0 , built from source with intel mkl, tried using normalize over an histogram, but got UndefVarError, see below:

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9* (2018-08-08 20:58 UTC)
Platform Info:
OS: Linux (x86_64-linux-gnu)
CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)

julia> using StatsBase

julia> h =fit(Histogram, randn(10000), nbins=50, closed=:right);

julia> normalize(h, mode=:pdf)
ERROR: UndefVarError: normalize not defined
Stacktrace:
[1] top-level scope at none:0

although the normalize and normlalize! functions exist in

~/.julia/packages/StatsBase/NzjNi/src/hist.jl:394 and :480

any suggestion? what am I doing wrong?

**Comment by oschulz** [comment]
@avigliotti , normalize is no longer in Base on Julia 1.0, but in LinearAlgebra. Your example should work if you add `using LinearAlgebra`.

**Comment by avigliotti** [comment]
yes, it does, many thanks! I haven't been working with Julia since 0.4-ish, and I'm slowly keeping up.

many thanks for the quick reply!
