### ISSUE TITLE
Histogram Documentation

### ISSUE THREAD

**Issue by alanedelman** [JuliaStats/StatsBase.jl#232]
In the doc,  I would really appreciate having a few examples of plotting histograms 
perhaps using Plots, PyPlot, etc. 
  Rather than the attitude that this is another packages problem, I'd err on
the side of helping the user with what he really wants to know right now.

**Comment by andreasnoack** [comment]
But it is the problem of another package. This package is for core computational functionality for statistics. It is not meant as the go-to package for high level statistical computations. The plan is to make a batteries-included statistics package that loads a lot of useful stuff but nobody has done that work yet.

**Comment by andreasnoack** [comment]
In particular, this package will not load any plotting libraries.
