### ISSUE TITLE
Weighted sampling without replacement

### ISSUE THREAD

**Issue by bkamins** [JuliaStats/StatsBase.jl#238]
Under Julia 0.5 and StatsBase 0.13.1 it seems that weighted sampling without replacement does not work correctly (unless I am not understanding how this sampling should be used).

Consider the code:
```
a = [1:10;]
wv = WeightVec([zeros(5); ones(5)])
sample(a, wv, 1, replace=false)
```
produces `[2]` (which should not happen as weight of 2 is 0.0) and moreover it is always `[2]` so actually no sampling takes place.

**Comment by nalimilan** [comment]
This code was introduced in https://github.com/JuliaStats/StatsBase.jl/pull/176. Cc: @devmotion
