### ISSUE TITLE
use of non-global RNG

### ISSUE THREAD

**Issue by tawheeler** [JuliaStats/StatsBase.jl#240]
Reproducibility with random numbers is often critical for research or work. It would be nice to support passing in your own rng:

```julia
rng = MersenneTwister(17)
sample(rng, [1,2,3])
```

This echoes https://github.com/JuliaStats/Distributions.jl/issues/436.

**Comment by richardreeve** [comment]
@matbesancon This is now fixed, and also works for all distributions, not just ones in `Random`, and so can be closed. I think it was fixed earlier, but in any event post JuliaStats/Distributions.jl#830 it definitely works:
```julia
julia> Random.seed!(rng, 1);

julia> sample(rng, [1,2,3])
3

julia> Random.seed!(rng, 1);

julia> sample(rng, [1,2,3])
3

julia> Random.seed!(rng, 1);

julia> sample(rng, [1,2,3])
3
```
