### ISSUE TITLE
Bug in Histograms with uneven bins

### ISSUE THREAD

**Issue by mkborregaard** [JuliaStats/StatsBase.jl#241]
For histograms with uneven bins, the height of bins must be normalized so that wider bins don't get higher bars. By convention, this is done by dividing the bin heights with the bin widths, so that the area of each bin, in the units on the X axis, is equal to the number of occurrences falling into that bin (not sure how this works for multidimensional histograms).
The current method fails to do so, which is a potentially problematic bug.

**Comment by mkborregaard** [comment]
Unless of course this is not a bug, but reflects that you think of StatsBase.Histogram as primarily a convenient way of counting the number of occurrences in a bin. In that case, though, I think the pitfalls with the uneven bins case should be well documented as this may cause issues downstream. E.g. for plotting packages (like Plots) that may wish to depend on Histogram for doing histogram plots. 
It might also be good to include a weigh_uneven keyword or something like that. But the correct solution here depends on your philosophy about where to split the functionality of a histogram.

**Comment by oschulz** [comment]
> Unless of course this is not a bug, but reflects that you think of StatsBase.Histogram as primarily a convenient way of counting the number of occurrences in a bin

IMHO, that's exactly what it is - histograms shouldn't be normalized automatically, otherwise it would be impossible to access the counts per bin (and derive statistical uncertaincy, etc., depending on the process under study) in an analysis. Of course, when normalizing a histogram (#231), "uneven" bin widths must be taken into account.

**Comment by mkborregaard** [comment]
This PR https://github.com/JuliaStats/StatsBase.jl/pull/243 provides functionality to do the normalization.

**Comment by mkborregaard** [comment]
The discussion on that PR fully encompasses my concerns, so I will close this issue for clarity.
