### ISSUE TITLE
Documenter.jl

### ISSUE THREAD

**Issue by rofinn** [JuliaStats/StatsBase.jl#260]
It would be really nice if we could switch over to using Documenter.jl with automatic docs generation.

**Comment by ararslan** [comment]
Agreed, this has been on my to-do list for quite some time, I just haven't yet gotten around to it.

**Comment by nalimilan** [comment]
FWIW, the DataFrames docs where ported some time ago in https://github.com/JuliaStats/DataFrames.jl/pull/780 and https://github.com/JuliaStats/DataFrames.jl/pull/929. Should be helpful for inspiration.

**Comment by nalimilan** [comment]
I've started some work in this area, will open a PR when ready (just to avoid work duplication).
