### ISSUE TITLE
Unreasonable warning spam

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/StatsBase.jl#263]
I am using this line:
`mtd_bins, mtd_hist = (f = fit(Histogram, mtd, nbins=100); (f.edges[1], f.weights))`

I have never used the keyword argument "closed". Yet, everytime I run this on Julia 0.6 I get a huge spam of:
```
WARNING: Default for keyword argument "closed" has changed from :right to :left.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:64
 [2] _check_closed_arg at C:\Users\datseris\.julia\v0.6\StatsBase\src\hist.jl:11 [inlined]
 [3] #fit#64(::Symbol, ::Int64, ::Function, ::Type{StatsBase.Histogram{Int64,N,E} where E where N}, ::Tuple{Array{Float64,1}}) at C:\Users\datseris\.julia\v0.6\StatsBase\src\hist.jl:298
 [4] (::StatsBase.#kw##fit)(::Array{Any,1}, ::StatsBase.#fit, ::Type{StatsBase.Histogram{Int64,N,E} where E where N}, ::Tuple{Array{Float64,1}}) at .\<missing>:0 (repeats 2 times)
 [5] #fit#67(::Array{Any,1}, ::Function, ::Type{StatsBase.Histogram}, ::Array{Float64,1}, ::Vararg{Any,N} where N) at C:\Users\datseris\.julia\v0.6\StatsBase\src\hist.jl:310
```
(the stacktrace continues even more).

Can you maybe remove this, pretty please? Since you have a documentation, you can have a "Changelog" section.

EDIT: I just saw the source code, and I now realise that this is probably a bug and not intended to be shown on *every* use of the Histogram fit. (If I knew how to fix it I would do a PR)

**Comment by ararslan** [comment]
The deprecation is intended to be somewhat loud, as it's designed to alert the user that without a change to their code, what they've written will do something different in the next release. It's important to make that obvious, since not everyone follows package development. To make it go away, the `closed` keyword argument should be specified in the user's code.

That said, I don't believe it's intended to be issued from every use of the deprecated signature, as (IIRC) `Base.depwarn` calls `Base.warn_once`.

**Comment by Datseris** [comment]
You are right, if I use the keyword `close = :left` the warning goes away. But still, if I Don't use it the warning shows up *every single time*

**Comment by ararslan** [comment]
It's probably because the warning comes from the function signature itself rather than from within the function body. @nalimilan, can you think of a better way we could structure it to avoid repeated warnings like this?

**Comment by andreasnoack** [comment]
There is a bug in `depwarm` when applied to constructors. I've found the issue and I might be able to fix it but having a silent `depwarn` still adds a ton of overhead. How long are we planning to keep it around for?

**Comment by ararslan** [comment]
This has the potential to be pretty subtly breaking if we remove the deprecation too hastily, so I'd probably prefer to let keep being obnoxiously loud until people provide the `closed` argument more consistently.

**Comment by Datseris** [comment]
That is fine if you want to keep it: my only suggestion is to change what the dep-warn says. Make it also say that the dep-warn goes away if you explicitly provide the keyword argument. (I did not know that until you guys told me)

**Comment by ararslan** [comment]
That's a good idea.

**Comment by nalimilan** [comment]
Deprecations aren't printed by default on Julia 1.5 and above.
