### ISSUE TITLE
Weighted sampling with replacement

### ISSUE THREAD

**Issue by ludkinm** [JuliaStats/StatsBase.jl#265]
Taking a weighted sample with replacement of length one does not return as expected when weights vec contains some zeros. (At least if in the first two positions.)
Digging into the sampling.jl it seems that there are three methods for sampling with replacement:
efraimidis_a
efraimidis_ares
efraimidis_aexpj
The method called from wsample is efraimidis_aexpj which does not return as expected.

I think the issue lies on these lines (565, 570, 574 and 579:
```julia 
pq[i] = (wv.values[i]/randexp() => i)
...
@inbounds threshold = pq[1].first
...
w = wv.values[i]
...
t = exp(-w/threshold)
```
So if `wv.values[1]=0.0`, then `pq[1].first = 0` and `t=NaN`. This ruins the priority queue.

MWE:
```
a = [1;2;3]
p = weights([0;0;1])
sample(a,p,1) # [3]
sample(a,p,2) # [3;3]
sample(a,p,2;replace=false) # [3;2]
sample(a,p,1;replace=false) # [2] but should be [3]
```

**Comment by nalimilan** [comment]
Can you try with git master (`Pkg.checkout("StatsBase")`)? This should have been fixed in https://github.com/JuliaStats/StatsBase.jl/issues/238.
