### ISSUE TITLE
Cholesky-like covariance decomposition

### ISSUE THREAD

**Issue by papamarkou** [JuliaStats/StatsBase.jl#29]
Is there a function anywhere in Julia stats (or linear algebra) similar to MATLAB's cholcov function? Here is the relevant MATLAB link in their help stats documentation:

http://www.mathworks.co.uk/help/stats/cholcov.html

I need this for some work I am doing, so any help is appreciated.

**Comment by ekinakyurek** [comment]
I tried same example in Julia1.1, am I doing something wrong?

```JULIA
julia> C1
4×4 Array{Int64,2}:
 2  1  1  2
 1  2  1  2
 1  1  2  2
 2  2  2  3

julia> cholesky(C1, Val(true))
ERROR: RankDeficientException(1)
```

```
```
