### ISSUE TITLE
Base.iszero not defined for Distributions.ZeroVector

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/StatsBase.jl#290]
Currently,

    iszero(Distributions.ZeroVector(Float64, 4))

results in

    ERROR: MethodError: no method matching zero(::Distributions.ZeroVector{Float64})

so things like

    iszero(mydistribution.µ)

don't work.

**Comment by andreasnoack** [comment]
Would you mind submitting a PR for this?

**Comment by oschulz** [comment]
Will do - but oops, I hit the wrong repo, this concerns Distributions, not StatsBase. Will reopen there. Sorry!
