### ISSUE TITLE
Please state in docstrings the normalization of autocor and crosscor

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/StatsBase.jl#294]
One can show [analytically](https://math.stackexchange.com/questions/1518206/finding-the-autocorrelation-of-a-sine-wave) that the autocorrelation of a sine or cosine signal `cos(t)` is `0.5cos(τ)` with `τ` the delay, aka lag.

This MWE:
```julia
using StatsBase
t = 0:0.01:200π
x = cos.(t)
a = autocor(x)
``` 
produces clearly `a = cos(τ)` instead of `a = 0.5cos(τ)`. Why? (because you normalize with std^2)

What is the normalization you are using? Looking at the source code I can see that it is the `dot(x,x)`. Since there are so many different digital processing and timeseries analysis books and each scientist may use a different approach (I have seen some normalizing by the std^2 of the signal (so that the autocor is 1 at τ=0) and some others only by the length), could you consider stating the normalization in the docstrings?

EDIT: Sorry if it wasn't obvious from my question: It is clear after looking at the source that you normalize for the std squared so that the correlation is always 1 at 0. But since there are also other approaches, you could add *only one* sentence to the doc strings to make people avoid looking at source (or just assuming you do this normalization).

**Comment by joshday** [comment]
I think the function you're looking for is `autocov`, and the main issue here is that statisticians and signal processing folks use the same name for slightly different things.  I'm sure a PR for the docstring would be appreciated if you'd be willing to make the distinction more clear.

**Comment by Datseris** [comment]
I would gladly make a PR to make the docs a bit more clear since I get the okay from here.

Since this isn't my package I didn't want to do work that may not get accepted.
