### ISSUE TITLE
Help with Histogram, please

### ISSUE THREAD

**Issue by ezaron** [JuliaStats/StatsBase.jl#299]
I recently upgraded to Julia 6.0.0 and discovered that the hist function had disappeared.

Now it seems there is a StatsBase.Histogram, but I am not sure how to use it. The documentation is a little opaque about how to access the components of the ::Histogram type, which seems to be the result of fit(StatsBase.Histogram,randn(1000,)), for example. I am looking for a vector containing the count of occurrences with within evenly spaced bins, or similar.

I someone could point me to a simple usage example, I would be most appreciative. In the meantime I will look at the source code and also be RTFM'ing to find out how to discover the inner workings of the type.

All the best,
Ed

**Comment by ararslan** [comment]
Hi Ed, we use the issue tracker for bug reports and feature requests. For questions, please use [Discourse](https://discourse.julialang.org). Thanks!
