### ISSUE TITLE
Doc issue(?): maximum absolute deviation/median absolute deviation

### ISSUE THREAD

**Issue by randyzwitch** [JuliaStats/StatsBase.jl#304]
(Continued from Slack)

I think this is just a docstring error, since the non-mutating function uses the mutating internally (`mad()` vs `mad!()`)

https://github.com/JuliaStats/StatsBase.jl/blob/9d851b704cc135ee4ca9bf68f9b0541d64d5814f/src/scalarstats.jl#L239-L269

If it's median, I can quickly submit a PR (or someone else who can confirm can just change it real quick)

**Comment by nalimilan** [comment]
Thanks. I think it's quite clear it's "median", so a PR would be welcome.
