### ISSUE TITLE
Feature request: add probabilities to correlations

### ISSUE THREAD

**Issue by tantrev** [JuliaStats/StatsBase.jl#307]
Pretty self-explanatory: would just be nice to have some sort of probability calculation with the correlation codes.

**Comment by nalimilan** [comment]
Could you develop what you mean?

**Comment by tantrev** [comment]
Yes, of course!

So, Scipy will calculate a p-value based on the "The two-sided p-value for a hypothesis test whose null hypothesis is an absence of association".  The underlying code Scipy uses may be found [here](https://github.com/scipy/scipy/blob/master/scipy/stats/mstats_basic.py), and the help pages for its [Kendall](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.kendalltau.html), [Spearman](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html), and [Pearson](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html) methods.

Though a different topic, there is also a faster algorithm to calculate Kendall Tau values, as documented [here](https://github.com/scipy/scipy/issues/1526) and in this [paper](https://link.springer.com/article/10.1007/BF02736122).

**Comment by nalimilan** [comment]
Well, there are two different questions. We already support Spearman and Kendall correlations, in addition to Pearson: http://juliastats.github.io/StatsBase.jl/stable/ranking.html#Rankings-and-Rank-Correlations-1

Then there's the question of hypothesis tests, which are in HypothesisTests.jl. I'm not sure which test you refer to exactly, but it might be there:
http://juliastats.github.io/HypothesisTests.jl/stable/parametric.html#Power-divergence-test-1

Else, feel free to open an issue in that repo.

**Comment by tantrev** [comment]
Thank you for the quick reply, and my apologies for the divergent question.  Let me just take a step back and clarify my use case: I would like to calculate correlations and p-values (or even just t-values would be best) as fast as possible on large datasets.  That being said, many hypothesis tests can be re-written in terms of correlation, as utilized in [Matrix eQTL](https://adairama.wordpress.com/2012/02/03/matrix-eqtl-ultra-fast-eqtl-analysis/).  JuliaStats' hypothesis test functions are currently not written to re-use information from correlation calculations.

Since I already mentioned it (as you pointed out, I really should've just made another ticket), I'll also try to clarify about the correlation code.  I understand that JuliaStats already calculates Spearman, Kendall, and Pearson correlations.  The suggestion I was trying to make is that I suspect JuliaStats' Kendall correlation code uses a slow algorithm that executes in O(n^2) time, as opposed to the linked algorithm with O(n*log(n)) time.

**Comment by nalimilan** [comment]
Then please file one ticket for each issue you want to discuss, including a detailed explanation. Also, any requests about tests should be filed in HypothesisTests.jl.
