### ISSUE TITLE
Design of the frequency/contingency tables

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/StatsBase.jl#32]
Efficient implementation of such functions on generic data types (e.g. strings) can be done via pooled data arrays. Therefore, I feel that it makes sense to implement these in the DataArrays.jl, and thus take advantage of the pooled arrays stuff.

For the Stats.jl package, we will still maintain the `counts` function that can be used to compute such tables based on integer variables, like

``` julia
counts([1, 1, 1, 2, 2, 2, 3, 3, 3, 3], 1:3)  # ==> [3, 3, 4]
```

We may also continue to the keep the `countmap` function (or whatever we finally decide to call it). 

What I suggest is to implement two-way or multi-way contingency tables in DataArrays.jl

---

Please look below to see my detailed consideration about the interface design.

**Comment by scidom** [comment]
Has there been any discussion held elsewhere or has anyone been working on a cross-tabulation routine? It is a rather fundamental descriptive statistic needed in a range of applications, from epidemiology to machine learning (to measure miss-classification) for example, so it would be really great to hear that someone is interested in coding it. Even if it is not the most efficient implementation at its outset, it would be good to have a first simple implementation for the sake of making such basic functionality available in Julia.

**Comment by nalimilan** [comment]
Have a look at my FreqTables.jl package mentioned above. I think this approach works and could be extended if needed.

**Comment by scidom** [comment]
Thanks, @nalimilan, yes, your FreqTables package seems useful. I will let you know in the next few days if I have any questions about its interface, as I will make use of it. Have there been any discussions about integrating your work into StatsBase given how fundamental cross-tabulation is for descriptive stats?

**Comment by nalimilan** [comment]
> Have there been any discussions about integrating your work into StatsBase given how fundamental cross-tabulation is for descriptive stats?

Not that I know of. But first we would need to agree on the design of `NamedArray`s, which would become a dependency of StatsBase.

**Comment by scidom** [comment]
All right, I can use your package for now, as it sounds that making a decision on `NamedArray` may take a long time.

**Comment by mkborregaard** [comment]
Trying again in May 2016 - are basic contingency tables really not yet a part of base Julia?

**Comment by nalimilan** [comment]
@mkborregaard As I noted above, see https://github.com/nalimilan/FreqTables.jl.

**Comment by mkborregaard** [comment]
OK, thanks, I have downloaded it and it does what it should. Sorry for sounding annoyed, I was just looking desperately for this functionality while stuck in a plane for 9 hours :-)

**Comment by Nosferican** [comment]
Should this be closed?

**Comment by nalimilan** [comment]
I guess so. It's too bad we don't have
