### ISSUE TITLE
StatsBase Implementation of Latin-Hypercube Sampling

### ISSUE THREAD

**Issue by bisraelsen** [JuliaStats/StatsBase.jl#323]
I have found an implementation of [Latin-Hypercube sampling](https://en.wikipedia.org/wiki/Latin_hypercube_sampling) in the [BlackBoxOptim](BlackBoxOptim.jl/src/utilities/latin_hypercube_sampling.jl) package, but I think the application is broader than that.

Do you think it belongs in the StatsBase package? If so I would be interested in developing a more full-featured version of it using the Matlab implementation as a guide.

**Comment by ParadaCarleton** [comment]
For future reference or anyone finding this in the future, try [QuasiMonteCarlo.jl](https://github.com/SciML/QuasiMonteCarlo.jl).
