### ISSUE TITLE
crosscor() function vs. the one in Python

### ISSUE THREAD

**Issue by Duls91** [JuliaStats/StatsBase.jl#324]
I want to perform a cross-correlation with two 2d arrays (both 5X5). Using crosscor() returns a 9x5x5 array. What I would like is the cross-correlation matrix of dims M+N-1, such as the output of the scipy.signal.correlate2d from Python, giving a 9x9 Matrix. 
Here is my code:

```
a = ones(5,5)
b = ones(5,5)
crosscor(a,b, demean=false)
```
Output: 
9×5×5 Array{Float64,3}:

What kind of cross-correlation is implemented here? I am having a hard time grasping this.
If I use the 2D convolution with a reversed array, I do get what I want:
`conv2(a,b[end:-1:1,end:-1:1])`
Output: 
9×9 Array{Float64,2}

but the implementation is FFT-based. I would like a direct convolution, but I cannot find one in Julia.

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
