### ISSUE TITLE
WIP: Faster `countmap` for small bit type e.g. Int8, UInt8, UInt16, Int16, Float16

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaStats/StatsBase.jl#334]
These bits can only have 256 or 65536 distinct values. Instead of using (radix)sorting or `Dict` one can simply use an array (of size 256 or 65536) to hold and accumulate the results.

From my own testing it will result in 9x-3x speed up. See [this gist](https://gist.github.com/xiaodaigh/2f7f65b7503068e495a8a94d8b03a738) for example implementation

**Comment by nalimilan** [comment]
Makes sense. Feel free to make a PR. Having a special case for `Float16` doesn't sound worth it, though, it doesn't seem very common to compute the frequency of floating point numbers, and `Float16` is a very specific type.

**Comment by xiaodaigh** [comment]
Implemented in #339

**Comment by xiaodaigh** [comment]
merged #339
