### ISSUE TITLE
Allow numeric Vectors as weights

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaStats/StatsBase.jl#335]
When I first started using `countmap` I was confused about how to do a count with weights. I thought `countmap(x, wgt)` would do where `wgt` is a numeric vector. But actually we need `countmap(x, weights(wgt))`. 

When I looked into the documentation there are 3 types of weights: they are Analytical, Frequency and Probability; these seem to be useful. But before reading the source code I only thought of weights as a numeric weight for each value and I suspect a lot of people would think like that too.

So do you think it's ok to add this signature?
`countmap(Vector{T}, Vectr{S}) where {T, S<:Number}`

**Comment by rofinn** [comment]
Quickly scanning the code it looks like we could probably just change the existing signatures.

[line 355](https://github.com/JuliaStats/StatsBase.jl/blob/master/src/counts.jl#L355):
```julia
countmap(x::AbstractArray{T}, wv::AbstractWeights{W}) where {T,W}
```
to 
```julia
countmap(x::AbstractArray{T}, wv::AbstractVector{W}) where {T,W<:Real}
```

line [320](https://github.com/JuliaStats/StatsBase.jl/blob/master/src/counts.jl#L320)
```julia
addcounts!(cm::Dict{T}, x::AbstractArray{T}, wv::AbstractWeights{W}) where {T,W}
```
to
```julia
addcounts!(cm::Dict{T}, x::AbstractArray{T}, wv::AbstractVector{W}) where {T,W<:Real}
```

**Comment by xiaodaigh** [comment]
Ok. I think keeping other signatures are fine. But the one that makes the most sense to me are just a straight weight vector of numerics

**Comment by rofinn** [comment]
Right, but doesn't the domain of the numerics matter (e.g., passing a vector of floating point values doesn't really make sense)?

**Comment by xiaodaigh** [comment]
yeah we associate count a with something a discrete. But i think it's ok have negative and floating point weights. Some may want to use it.

**Comment by nalimilan** [comment]
> FWIW, I'm not sure it makes sense to call this method with anything other than FrequencyWeights (or maybe an AbstractVector{Int}).

Actually, that's a complex issue. It can make sense to show the sum of analytic or probability weights, even if that's not necessarily an integer number. It's useful in particular to compute proportions. Stata's `tabulate` command [appears](https://www.stata.com/statalist/archive/2004-03/msg00660.html) to compute the sum of analytic weights (after scaling them to sum to the number of observations). OTOH, it does not [appear](https://www.stata.com/statalist/archive/2010-03/msg00684.html) to support probability weights.

Given that treating weights as frequency weights is more natural in most cases (i.e. for frequency weights, probability weights and when the type isn't specified), I wonder whether it's worth having a special case for analytic weights.

**Comment by rofinn** [comment]
Hmmm, seems weird to support analytic weights and not probability weights, but I'd be fine with special casing them and assuming frequency weights otherwise.

**Comment by ssfrr** [comment]
Came across this with `sample`. As an example, I want to sample from `x = [1, 2, 3]`, with weights `w = [1, 2, 1]`, i.e. `2` should be twice as likely as `1` or `3`. it would be nice to just do `sample(x, w)`.

As it stands it took a bit of time to look at the docs, understand what the different types of `AbstractWeight`s do, and figure out that I could do `sample(x, weights(w))`.

**Comment by nalimilan** [comment]
See also discussion at https://github.com/JuliaStats/StatsBase.jl/issues/443.
