### ISSUE TITLE
the fate of midpoints

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/StatsBase.jl#344]
The [release notes](https://github.com/JuliaLang/julia/blob/aea91558d3b60bf6d2bcdbd608b369e28ffffc9f/HISTORY.md) of `v0.6` suggest that `midpoints` was moved to `StatsBase.jl`. It is [exported](https://github.com/JuliaStats/StatsBase.jl/blob/43b502302bb25dfaad0d9676e9de6d9bab675aa5/src/StatsBase.jl#L133), but othewise undefined, so it is basically `Base.midpoints` for `v0.6`, with deprecation warnings, and undefined in `v0.7`.

The function itself is very useful since it can calculate midpoints cheaply for regular grids (eg `StepRangeLen`). It would be great if it could be defined in this package.

**Comment by nalimilan** [comment]
It's been removed by https://github.com/JuliaStats/StatsBase.jl/pull/144 because Base included the same function. We should probably re-add it now that it's no longer in Base. Can you make a PR? Maybe leave some time in case somebody objects, though.

**Comment by andreasnoack** [comment]
I'd be in favor of adding it again.

**Comment by tpapp** [comment]
I made a PR, #345.

**Comment by tpapp** [comment]
The PR is merged so this issue can be closed.

Please consider tagging a release, it would help me get rid of some deprecation warnings and provide a smooth transition path to `v0.7` for some packages.
