### ISSUE TITLE
Naming for mad()?

### ISSUE THREAD

**Issue by mikkling** [JuliaStats/StatsBase.jl#347]
I'm just learning Julia, and it took a while to find out what was wrong with the code for my simple outlier detection algorithm test -- turns out that mad() doesn't yield the expected median of the absolute deviations from the median... 

I looked at earlier issues in StatsBase about MAD and found this (https://github.com/JuliaStats/StatsBase.jl/issues/197): 

"Just to be clear, constant is what make this function produce a consistent estimator of the standard deviation for normally distributed data. So if you intend to remove it, you need to either decide that (a) your estimator is inconsistent or (b) you don't provide any mechanism for producing the number some people believe MAD should generate."

This is certainly a good function, but perhaps it could be named something that indicates that it estimates standard deviation? I, for one, was expecting a function named mad to yield by-the-book MAD. 

[This is also my very first post on GitHub. Sorry if I offend against proper posting conventions!]

|m|
Mikael

**Comment by nalimilan** [comment]
Yes, I think at the very minimum the docs should mention this.

@ararslan Wasn't it a bit radical to stop documenting what `mad` actually returns while removing the argument in https://github.com/JuliaStats/StatsBase.jl/pull/198? I'm also not convinced it was a good idea to remove that argument: what problem does it create? At least it seems the OP is one counter-example to @andreasnoack's statement that nobody uses it.

FWIW, [MATLAB](https://fr.mathworks.com/help/stats/mad.html) doesn't apply any multiplicative factor. OTOH R and Numpy's StatsModels apply it by default, but provide an argument to change it. I really think we should do the same.

**Comment by ararslan** [comment]
> Wasn't it a bit radical to stop documenting what mad actually returns while removing the argument in #198?

Yeah, probably. I guess that didn't occur to me nearly two years ago. 😛 Definitely a good idea to improve the documentation for it.

**Comment by nalimilan** [comment]
OK. Thoughts about reintroducing that argument while we're at it, given that other software provide it?

**Comment by mikkling** [comment]
Thank you for prompt feedback!

So far, i'm loving Julia. Thank you for making it even better!


|m|
Mikael

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/StatsBase.jl/pull/349.
