### ISSUE TITLE
midpoints function have type dispatch conflict

### ISSUE THREAD

**Issue by jingpengw** [JuliaStats/StatsBase.jl#351]
these two functions have conflict
https://github.com/JuliaStats/StatsBase.jl/blob/master/src/hist.jl#L533
```julia
julia> Range <: AbstractVector    
true                              
```

**Comment by andreasnoack** [comment]
Could you elaborate? What is the specific issue? An example would be best.

**Comment by jingpengw** [comment]
it is just some warnings.
```julia
julia> using StatsBase
WARNING: Method definition midpoints(Base.Range{T} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /usr/people/jingpeng/.julia/v0.6/StatsBase/src/hist.jl:535.
WARNING: Method definition midpoints(AbstractArray{T, 1} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /usr/people/jingpeng/.julia/v0.6/StatsBase/src/hist.jl:533.
```

**Comment by nalimilan** [comment]
Fixed in the latest version, see https://github.com/JuliaStats/StatsBase.jl/pull/348.

**Comment by jingpengw** [comment]
thanks, the function just not exported, still have type conflict though.

**Comment by nalimilan** [comment]
Can you be more specific?

**Comment by jingpengw** [comment]
Range is a subtype of AbstractVector, so the midpoints function will have duplicated dispatch?

**Comment by nalimilan** [comment]
What is "duplicated dispatch"?

**Comment by jingpengw** [comment]
I mean `Range` is subtype of AbstractVector, the runtime could be confused
if the input is a type of Range.

**Comment by ararslan** [comment]
`Range` is strictly more specific than `AbstractVector`, so if a method is defined in terms of `AbstractVector` only then dispatch will use it, and if there are methods for both `Range` and `AbstractVector`, dispatch will use the former.
