### ISSUE TITLE
annoying warning

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaStats/StatsBase.jl#354]
Hi, I am getting this warning over and over again when my package precompiles
```
WARNING: Method definition midpoints(AbstractArray{T, 1} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /home/febbo/.julia/v0.6/StatsBase/src/hist.jl:533.

```
Any suggestions to eliminate it? I assume that it was fixed, but the package manager makes me use an old version.

I am not sure which one of my dependencies has a StatsBase dependancy.

Thanks!

**Comment by andreasnoack** [comment]
Dup of #350, #351, and #353. The new version has just been merged into METADATA so please run `Pkg.update()`

**Comment by huckl3b3rry87** [comment]
@andreasnoack sorry that I did not notice the other issues.
