### ISSUE TITLE
Changes of dims argument in sum, mean, ... in v0.7.0-DEV

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/StatsBase.jl#360]
I started a `db/0.7` branch of this package to work on conversions for Julia v0.7.0

One of the important changes for this package in Julia v0.7.0 is changing `dims` to be a named argument in many `Base` functions that are extended here.  Picking up the changes in `sum` calls is fairly easy but changing calls to `mean`, `var`, `std`, etc. has turned into a game of whack-a-mole.  The calling sequence for certain `mean` methods in `Base` has changed between v0.6.2 and v0.7.0-DEV.  There is a `Compat.mean` function that can translate a call in the v0.7 style to one for v0.6.2 but it is not always clear if that should be done.  The method signatures from this package have not been modified to the 0.7 style and, of course, are not in `Compat`.

The result is that one has to be very careful when deciding if a call to `mean` should be changed to `Compat.mean`.

Long term I imagine that the `mean`, `std`, `var`, etc. methods defined here should adopt the "named `dims` argument" convention but that would require a deprecation period.  The short term would be to get a version of `StatsBase` that passes tests on Julia v0.7.0-DEV without too many deprecation warnings.

It seems that it is going to be tricky to have the same code base test cleanly in both v0.6.2 and v0.7.0-DEV.  Perhaps it would be best to create a branch in which the minimum Julia version is v0.7.0-DEV.4064 (when named "dims" arguments were introduced) and proceed from there.

I think I am not doing this efficiently and would appreciate suggestions on how to proceed.

**Comment by nalimilan** [comment]
We could decide that master requires 0.7 from now on, and we can still create a 0.6 branch if we have to backport fixes. But it's also quite effective to have 0.6 and 0.7 side by side under `VERSION` checks. Femtocleaner will automatically remove the blocks when we require 0.7.

**Comment by ararslan** [comment]
If we're changing our own APIs to follow those of Base, I think we should just solidly require 0.7 without maintaining two separate APIs inside of version checks. If we _aren't_ changing our own APIs and we're just fixing deprecation warnings due to not using `dims=` in internal calls, it should be safe to just prefix calls to `sum`, `mean`, et al. with `Compat.`.

**Comment by ufechner7** [comment]
What is the current status? How can I get a working StatsBase for 0.7alpha?

**Comment by Nosferican** [comment]
I believe is working right now. I had `depwarn-no`, but I think checking out the master branch should get it to work.

**Comment by nalimilan** [comment]
It just works with StatsBase 0.23.
