### ISSUE TITLE
norepeat function in src/misc.jl seems both expensive and wrong

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/StatsBase.jl#361]
Currently the function is defined as
```julia
function norepeat(a::AbstractArray)
    sa = sort(a)
    for i = 2:length(a)
        if a[i] == a[i-1]
            return false
        end
    end
    return true
end
```

I don't think it is necessary to sort the contents.  Using a `Set` and checking each element before adding is probably faster. Even if `sort(a)` should be used the check should be on adjacent elements of `sa` not of `a`.

**Comment by dmbates** [comment]
Addressed in https://github.com/JuliaStats/StatsBase.jl/pull/362/commits/ec43bc857f0db73fced59f6fe848081614af740f

**Comment by ararslan** [comment]
There's actually already a Base function for this: `allunique`. We should just deprecate `norepeat` to `allunique`.

If it wasn't for the sort, I would say that this function is checking that there are no contiguous repeated entries, but if it's modifying the order prior to checking then that's clearly not the case...

**Comment by dmbates** [comment]
I should know this but how does one deprecate a function in favor of another?

**Comment by dmbates** [comment]
Never mind.  I just noticed the `src/deprecates.jl` file.
