### ISSUE TITLE
Moving forward with standard deviation and standard error function names.

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsBase.jl#369]
Currently StatsBase has `std` for standard deviation and used `stderr` for standard error. Given the decision at Base to use `stderr` as one of the three input/output (I/O) connections, StatsBase must decide how to rename it.

Possible candidates include:
- `sd` and `se`
- `stddev` and `stderror`

Relevant discussions occurred in [julia PR#26636](https://github.com/JuliaLang/julia/pull/26636#comment-376861507), Slack #statistics, and #368.

**Comment by Nosferican** [comment]
Those are two very valid arguments.
```
stderror(model)
```
would still be a bit shorter than
```
sqrt.(diag(vcov(model)))
```
which is at least the longest the standard error function should be.

**Comment by nalimilan** [comment]
Why not, but if we rename `std` to `stddev`, we should do the same in Base.

**Comment by stevengj** [comment]
My suggestion would be to leave `std` as-is, and use `stderror` for the standard error.

The standard deviation is more common, and `std` mirrors `var`.

**Comment by ararslan** [comment]
Sure, that makes sense to me.
