### ISSUE TITLE
Weighted Sampling without replacement

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/StatsBase.jl#37]
We now support non-weighted sampling (with & without replacement) + weighted sampling with replacement.

Weighted sampling without replacement is not supported yet. This is not as easy to implement. 

A naive implementation might look like

``` julia
n = length(a)     # the pool size
k = length(dst)   # the number of samples to draw

for j = 1 : k
    i = wsample(1:n, w)  # sample a value in 1:n according to weights w
    x[j] = i
    w[i] = 0     # preclude i from being sampled in future
end
```

Unfortunately, this is _mathematically incorrect_.

Suppose `π` be the weights that sum to 1, and you want to draw `x1` and `x2` such that `x1 != x2`. Then the marginal distribution of `x1` is **not** `π`.  

This can be easily illustrated by the following simple example. Suppose `π = [0.4, 0.6]`, and you want to draw `x1` and `x2` that are different. Clearly, `(x1 = 1, x2 = 2)` and `(x1 = 2, x1 = 1)` should have the same joint probability, which means that the marginal probability of `p(x1 = 1)` equals `0.5` (instead of `0.4`).

A correct way to do this is _rejection sampling_, which may look like:

``` julia
x = wsample(1:n, w, k)   # draw a sample sequence (with replacements)
while there-are-repeated-sample(x)
    x = wsample(1:n, w, k)   # sample again
end
# until we get a sample sequence without repeated elements
```

This is very inefficient, as when `k` increases, it would become very unlikely to draw a sequence of which all elements are distinct.

Any suggestions?

**Comment by krlmlr** [comment]
@johnmyleswhite: Hi there ;-) I'm doing more work now on the [wrswoR package](https://github.com/krlmlr/wrswoR), and results are getting nicer. I'm wondering if it makes sense to create a proper C++ library, and simply add R and Julia bindings?

**Comment by johnmyleswhite** [comment]
@krlmlr: That would be really great. If you're going that route, perhaps you might consider using C or Fortran instead, given C++'s lack of a coherent ABI on many platforms?

**Comment by krlmlr** [comment]
That would be necessary for inclusion into base R, too. In C++ I can say `std::priority_queue` or `std::partial_sort` -- what would be a good C library to depend on?

**Comment by johnmyleswhite** [comment]
I'm not sure: I tend to write everything from scratch when I write C code (which I do very rarely).
