### ISSUE TITLE
Promotion in mad

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/StatsBase.jl#370]
The `mad` function doesn't handle promotion of e.g. `Rational`. We should probably just `float` in https://github.com/JuliaStats/StatsBase.jl/blob/f70a0128160291d7ab4ae88b01b419a3baa627fa/src/scalarstats.jl#L283. That would be type unstable for `Rational` but not the more important `FloatX` or `Int` cases.

**Comment by Nosferican** [comment]
Doesn't the `promote_type` take care of that?
```
v = [1//2, 1//3]
T = eltype(v)
S = promote_type(T, typeof(middle(first(v))))
v2 = LinearAlgebra.copy_oftype(v, S)
center = median!(v2)
v2 .= abs.(v2 .- center)
m = median!(v2)
```

```
v = [25e-2, 5e-1]
T = eltype(v)
S = promote_type(T, typeof(middle(first(v))))
v2 = LinearAlgebra.copy_oftype(v, S)
center = median!(v2)
v2 .= abs.(v2 .- center)
m = median!(v2)
```

```
v = [2, 3]
T = eltype(v)
S = promote_type(T, typeof(middle(first(v))))
v2 = LinearAlgebra.copy_oftype(v, S)
center = median!(v2)
v2 .= abs.(v2 .- center)
m = median!(v2)
```

**Comment by nalimilan** [comment]
@andreasnoack Do you have a reproducer of the problem you mentioned?

**Comment by andreasnoack** [comment]
Should have added one when I files. This might simply have been fixed. I'm unable to reproduce.
