### ISSUE TITLE
Add bar and or plot overload on Histogram

### ISSUE THREAD

**Issue by JMurph2015** [JuliaStats/StatsBase.jl#373]
A lot of the time that people are making histograms, it's to immediately plot them.  Can StatsBase add some sort of functionality like this function I've made for my personal hacking?
```julia
import PyPlot.bar
bar(x::StatsBase.Histogram) = bar(x.edges[1][1:end-1], x.weights)
```

**Comment by andreasnoack** [comment]
This is supported by `Plots` which uses `StatsBase.Histogram` underneath.
