### ISSUE TITLE
Any reason not to allow sorting of PValues?

### ISSUE THREAD

**Issue by kescobo** [JuliaStats/StatsBase.jl#378]
I was recently trying to rank order `PValue`s in some results to implement Benjamini-Hochberg multiple hypotheses correction and ran into the problem that `isless()` is not defined for `PValue`s:

```
julia> using StatsBase

julia> ps = StatsBase.PValue.(rand(10));

julia> sort(ps)
ERROR: MethodError: no method matching isless(::StatsBase.PValue, ::StatsBase.PValue)
```

Is there some theoretical reason for this, or is it just that no one has bothered to implement it?

(Incidentally, I was going to ask what the best place to put BH correction, and found that of course someone's [already done it](https://github.com/juliangehring/MultipleTesting.jl))

**Comment by ararslan** [comment]
> Is there some theoretical reason for this

Nope

> or is it just that no one has bothered to implement it?

Yep

AFAIK the only reason that type exists is so that we can enforce 0 <= p-value <= 1. Perhaps there's a better way than a dedicated type. I actually don't know that any packages use it; for example, HypothesisTests has a `pvalue` function and it just returns a plain ol' `Float64`.

**Comment by kescobo** [comment]
>I actually don't know that any packages use it

Ahh, interesting. I got mine out of GLM.jl's `coeftable`. It's trivial enough to just grab to value out of it, but is there some julian way of expressing "use methods for this field for the following functions?" MKBorregard uses a `@forward_func` macro in EcoJulia - wondering if there's a different preferred way.

**Comment by nalimilan** [comment]
We could probably get rid of `PValue`. It's only useful to check the range and for pretty-printing, but that could be handled directly from the `show(::CoefTable)` method.

**Comment by nignatiadis** [comment]
@kescobo there is a well-tested Benjamini-Hochberg implementation in @juliangehring's [MultipleTesting.jl](https://github.com/juliangehring/MultipleTesting.jl) package.

Related to the issue at hand, the MultipleTesting.jl package defines a p-value vector type which takes care of enforcing $0 \leq P_i \leq 1$, as well as storing the minimum and maximum values.

```jl 
struct PValues{T<:AbstractFloat} <: AbstractVector{T}
```
