### ISSUE TITLE
Rename to Statistics.jl  

### ISSUE THREAD

**Issue by musm** [JuliaStats/StatsBase.jl#391]
There's also the meta package `Stats.jl` . Perhaps it's time to take a serious look at the packages in the org and how they should be organized. 

I think having the base package called `Statistics.jl` is good for discoverability, especially since some statistics features have been removed from base Julia.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/julia/issues/27374 and https://github.com/JuliaLang/julia/issues/27140 about moving StatsBase to stdlib, and https://github.com/JuliaStats/Stats.jl/pull/4 about reviving Stats.jl.
