### ISSUE TITLE
Make weight types immutable

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/StatsBase.jl#397]
Currently our weight types are defined to be mutable, and we even provide `setindex!`. That seems weird to me. Wouldn't it make more sense for them to be immutable, and if not, could someone explain why?

cc @rofinn and @nalimilan

**Comment by rofinn** [comment]
There are a couple situations where I've found it nice having mutable weights:

- Things like `reverse!(eweights(n, λ))` is slightly less tedious than `reverse!(values(eweights(n, λ)))`
- Being able to permute a temporary weight vector when dealing with missing data is nicer than making a new copy on each iteration or mutating the underlying values.

**Comment by Nosferican** [comment]
Status? I feel immutable is fine, for working with groups I always end up having to recompute the weights based on a subset, but am fine with that for now.

**Comment by nalimilan** [comment]
I don't see the point of disallowing mutation.
