### ISSUE TITLE
Has `linreg` moved here?

### ISSUE THREAD

**Issue by lhupe** [JuliaStats/StatsBase.jl#398]
If one calls `linreg` from `julia-0.7.0-beta2`, the `Base` function throws the following error
```julia
ERROR: linreg has been moved to the package StatsBase.jl.
Run `Pkg.add("StatsBase")` to install it, restart Julia,
and then run `using StatsBase` to load it.
```
Naturally, I followed the instructions, imported `StatsBase` (version 0.24.0) and restarted `julia` – however, nothing changed. `linreg` still calls the function from `Base` (as confirmed by the `@which` macro). 
Suspecting that `StatsBase` doesn't yet export `linreg`, I tried to access `StatsBase.linreg`, which in turn led to the deprecated function from `Base` being imported into `StatsBase`.

I repeated the above tests on the current `StatsBase` `master` to the same results.

All this has caused me to suspect that there is no `linreg` in this package.
Am I doing something horribly wrong or has the function simply not arrived at its new home yet?

**Comment by andreasnoack** [comment]
I think we lost it during the [back and worth](https://github.com/JuliaStats/StatsBase.jl/commit/cc9ad6ea170897ca2f817ca6b58fe26445bf29da) of the stats function from the main Julia repo. We should probably add it back here but do you really need `linreg` though? It can only do simple linear regression and doesn't provide uncertainty estimates so you might be better off with either `\` or the `GLM` package.

**Comment by lhupe** [comment]
Thanks for the quick response. No, I don't really _need_ `linreg`, however, I was trying to use it just now and the error messages confused me enough to open this issue. 
Thanks for pointing out `GLM`,  I wasnt aware of the package!

**Comment by andreasnoack** [comment]
In any case, this should be cleaned up. The current error messages are very confusing. Just wanted to mention that there might be better alternatives.

**Comment by nalimilan** [comment]
As I said elsewhere before, I'd rather not add `linreg` here given that it can confuse people due to its appealing name. Also that's a bug in Julia, not in StatsBase AFAICT.

**Comment by Datseris** [comment]
I think `linreg` is an excellent function that does something very precise and very well defined. There is no reason to go to [GML](https://github.com/JuliaStats/GLM.jl) which just looking at the documentation it is clear that it is already _way too complicated_ for such a trivial functionality.

If you have problem with the name just rename it.

**Comment by bjarthur** [comment]
bump

**Comment by bjarthur** [comment]
the error msg should make it easy for folks and say `linreg(x,y) == reverse([x ones(length(x))]\y)`

**Comment by nalimilan** [comment]
Would you make a PR?

**Comment by dmbates** [comment]
@bjarthur I think it can be written as
```julia
linreg(x, y) = hcat(fill!(similar(x), 1), x) \ y
```
avoiding the `reverse`

**Comment by brenhinkeller** [comment]
bump. 
Purposely letting this function die just because someone doesn't like the name seems awfully user-hostile to me, comes across as "users who aren't sophisticated enough to just use `\` by default can GTFO". It was a simple, convenient function that did one thing.

**Comment by JeffBezanson** [comment]
Whether the `linreg` function *should* exist is totally irrelevant here. As a matter of policy, it needs to have a functioning deprecation in v0.7, so this is just a bug. At a minimum, there can be a definition for it here that's conditional on julia v0.7.

**Comment by Nosferican** [comment]
I believe this can be closed.

**Comment by st--** [comment]
For anyone who comes across this issue in search of linear regression, I've registered a very simple [LinearRegression.jl package](https://github.com/st--/LinearRegression.jl), which does the basic least-squares regression without any expensive dependencies (and I refer to all the various packages I know of that implement fancier extensions to linear regression in the package README).
