### ISSUE TITLE
Any guarantee about covm, varm ?

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/StatsBase.jl#403]
```
julia> using StatsBase

julia> covm
ERROR: UndefVarError: covm not defined

julia> StatsBase.covm
covm (generic function with 8 methods)

julia> StatsBase.covm
covm (generic function with 8 methods)

julia> StatsBase.varm
varm (generic function with 10 methods)

```
that makes me very scared that at some point you will even remove `covm` and `varm`, which we currently use right now.

If you want to keep them, can you export them? If you won't keep them, can you please let us know as soon as possible?

**Comment by Datseris** [comment]
If this issue is weird to any developer reading it, be aware that it is well justified.

The `linreg` function which we have been using happily just magically dissapearred one day with out any plans of bringing it back. I just want to be sure that this won't happen to `covm, varm`, because I literally copied `linreg` to my packages to continue the functionality. 

https://github.com/JuliaStats/StatsBase.jl/issues/398

**Comment by ararslan** [comment]
`covm` and `varm` are in Base in 0.6 and in the Statistics stdlib package in 0.7. They were only in this repo very briefly between 0.7.0-beta and 0.7.0-beta2.
