### ISSUE TITLE
Typo in attribution of algorithm for Kendall correlation.

### ISSUE THREAD

**Issue by PGS62** [JuliaStats/StatsBase.jl#414]
Hi there,
The code for calculating Kendall's correlation (https://github.com/JuliaStats/StatsBase.jl/blob/master/src/rankcorr.jl) includes a comment attributing the algorithm to "Knigh JASA (1966)", but that should read "Knight JASA (1966)" - See https://www.jstor.org/stable/2282833?seq=1#page_scan_tab_contents

**Comment by andreasnoack** [comment]
Thanks for reporting. You can easily fix this by editing the file on GitHub.

**Comment by PGS62** [comment]
Thanks Andreas, I’ll have a go at that, which will be my first time making any kind of edit on GitHub. But a one character change to a comment is a start I suppose.

 

Kind regards

 

Philip

**Comment by andreasnoack** [comment]
Fixed by #415
