### ISSUE TITLE
Statistics from histogram

### ISSUE THREAD

**Issue by jw3126** [JuliaStats/StatsBase.jl#422]
I was surprised, that e.g. the following does not work:
```julia
julia> using StatsBase, Statistics

julia> h = fit(Histogram, rand(100), closed=:right)
Histogram{Int64,1,Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
edges:
  0.0:0.2:1.0
weights: [17, 23, 17, 21, 22]
closed: right
isdensity: false

julia> mean(h)
ERROR: MethodError: no method matching iterate(::Histogram{Int64,1,Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}})
```
Is this just not implemented or a concious design decision? Depending on the branch, are you interested in a PR / what is the recommended way to compute the mean of a histogram?

**Comment by oschulz** [comment]
Me and @lmh91 are preparing a package that makes histograms act as (empirical) distributions, and will (in addition to things like `rand`) also support `mean`, `var` and `cov`. The code is currently part of BAT.jl (see https://github.com/bat/BAT.jl/blob/master/src/distributions/HistogramAsUvDistribution.jl and https://github.com/bat/BAT.jl/blob/master/src/distributions/HistogramAsMvDistribution.jl), but we're planning to release it as a standalone package very soon.

**Comment by oschulz** [comment]
See also this related discussion: https://discourse.julialang.org/t/using-a-normalized-histogram-as-a-distribution/27682

**Comment by oschulz** [comment]
> Me and @lmh91 are preparing a package that makes histograms act as (empirical) distributions

[EmpiricalDistributions.jl](https://github.com/oschulz/EmpiricalDistributions.jl) is a registered package now.

**Comment by nilshg** [comment]
In light of this being a standalone package, can it be agreed that this won't be implemented in `StatsBase` and this issue be closed?
