### ISSUE TITLE
winsor implicitly sorts data

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/StatsBase.jl#437]
Eg
```julia
julia> winsor(collect(5:-1:1), prop = 0.2)
5-element Array{Int64,1}:
 2
 2
 3
 4
 4
```
but this is not reflected in the documentation, which is
>     winsor(x; prop=0.0, count=0)
>
> Return a copy of `x` with either `count` or proportion `prop` of the lowest
elements of `x` replaced with the next-lowest, and an equal number of the
highest elements replaced with the previous-highest.  To compute the Winsorized
mean of `x` use `mean(winsor(x))`.

and is not apparent from the example in the docstring either (because it is already sorted).

Suggestion: perhaps `winsor` should **not** sort, as that would make it easier to eg winsorize a `DataFrame` column.

**Comment by nalimilan** [comment]
I think it's more efficient to sort, but indeed it would make sense to avoid doing that by default.
