### ISSUE TITLE
how to update h.edges

### ISSUE THREAD

**Issue by lazarusA** [JuliaStats/StatsBase.jl#438]
Suppose I have: 

using StatsBase
h = fit(Histogram, rand(100), 0:0.1:1)
h.edges

and I want to update the object h.edges to 0:0.1:1.1 without fitting again(I want to keep the old counts). Is there a way around?

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
