### ISSUE TITLE
nicer ways to chain data transforms

### ISSUE THREAD

**Issue by gdkrmr** [JuliaStats/StatsBase.jl#452]
What is described [here](https://github.com/JuliaStats/MultivariateStats.jl/issues/86#issuecomment-456200537)  is really awkward. There should really be a nicer way to chain data transforms. I am not sure if `StatsBase.jl` is the right place to put this.

**Comment by nalimilan** [comment]
Why not discuss this in the MultivariateStats issue? That seems more relevant there.

**Comment by gdkrmr** [comment]
The `MultivariateStats` maintainers think it is "out of scope" of their package.

**Comment by wildart** [comment]
@gdkrmr  StatsBase & MultivariateStats have certain API interface design, so if you feel the need to extend it, you are welcome to propose a solution for discussion.
