### ISSUE TITLE
Quantiles with missing values: API inconsistency

### ISSUE THREAD

**Issue by tlienart** [JuliaStats/StatsBase.jl#467]
```julia
julia> x = [1,1,1,2,3,4,1];
julia> quantile(x)
5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 2.5
 4.0
julia> x=[1,1,1,2,3,4,1,missing];
julia> quantile(x) # errors, potentially ok
ERROR: MethodError: no method matching quantile(::Array{Union{Missing, Int64},1})
julia> quantile(skipmissing(x)) # errors, not ok
ERROR: MethodError: no method matching quantile(::Base.SkipMissing{Array{Union{Missing, Int64},1}})
julia> quantile(skipmissing(x), 0.5)
1.0
```

### Suggested fix

There's two approaches, either make `quantile(skipmissing(x))` work or make `quantile(x)` apply `skipmissing` internally (what's done below). 

```julia
quantile(v::AbstractArray{<:Union{Missing,Real}}) = quantile(skipmissing(v), [.0, .25, .5, .75, 1.0])
``` 

### Alternative fix

matches what's done in statistics.jl:

```julia
quantile(itr) = quantile(collect(itr), [.0, .25, .5, .75, 1.0])
```

happy to open a PR for this if deemed relevant?

**Comment by nalimilan** [comment]
`quantile` is defined in the stdlib Statistics module, not in StatsBase. Anyway it's intended that `quantile` throws in the presence of missing values (https://github.com/JuliaLang/julia/pull/27515): no functions in Julia automatically skip missing values for safety.

The fact that `quantile(x)` doesn't work applies to any array: you need to provide the probabilities.

**Comment by tlienart** [comment]
Right one way or another one of the two libs has something wrong since you *can* do this at the moment

```julia
quantile(skipmissing([missing, 1, 2, 3]), [0.0, 0.5])
```

and it's even documented https://github.com/JuliaLang/julia/blob/master/stdlib/Statistics/src/Statistics.jl#L882_916

do you suggest an issue gets opened on Julia then?

**Comment by nalimilan** [comment]
OK, there's an inconsistency in this package. The signature needs to be relaxed as in Julia. See also https://github.com/JuliaStats/StatsBase.jl/issues/449.

**Comment by nalimilan** [comment]
Wait, I thought you were referring to the weighted quantile method. What's the problem then?

**Comment by nalimilan** [comment]
Got it, the problem is actually due to the `quantile(::AbstractArray{<:Real})` method that really shouldn't be defined in this package. See https://github.com/JuliaStats/StatsBase.jl/issues/467.
