### ISSUE TITLE
Method for weighted mean with mismatched types is gone

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/StatsBase.jl#475]
The fallback treats the first argument as a function apparently??
```julia
julia> mean(Union{Int,Missing}[1,2,3], weights([1,2,3]))
4.666666666666667

julia> @which mean(Union{Int,Missing}[1,2,3], weights([1,2,3]))
mean(f, A::AbstractArray) in Statistics at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Statistics/src/Statistics.jl:76
```

**Comment by omus** [comment]
Would it also make sense to make `mean(f, A::AbstractArray)` be `mean(f::Base.Callable, A::AbstractArray)`?

**Comment by ararslan** [comment]
It would, but that method is defined in Statistics rather than StatsBase.

**Comment by omus** [comment]
The PR that removed `Callable`: https://github.com/JuliaLang/julia/pull/29692
