### ISSUE TITLE
Can't sample multidimensional arrays

### ISSUE THREAD

**Issue by amrods** [JuliaStats/StatsBase.jl#482]
I am opening a new issue here. I first mentioned it in [issue 161](https://github.com/JuliaStats/StatsBase.jl/issues/161) but didn't get attention. I think this is a very easy fix.

`sample` has trouble dispatching method 8 of the methods table:

```
sample(a::AbstractArray, dims::Tuple{Vararg{Int64,N}} where N; replace, ordered)
```

so `sample(1:100, (2,2))` gives a methods error:

```
julia> sample(1:100, (2,2))
ERROR: MethodError: no method matching sample!(::MersenneTwister, ::UnitRange{Int64}, ::Array{Int64,2}, ::MersenneTwister; replace=true, ordered=false)
```

I think this is because the rng argument is repeated in line 393 of sampling.jl

**Comment by nalimilan** [comment]
Thanks. Can you suggest a fix or make a pull request?
