### ISSUE TITLE
Feature request: Inequality Measures

### ISSUE THREAD

**Issue by jo-fleck** [JuliaStats/StatsBase.jl#485]
Are there plans to include some basic inequality measures (e.g. Gini)? I think this would be a worthwhile consideration.

There are already some codes available in forums such as this [one](https://stackoverflow.com/questions/31321810/gini-coefficient-in-julia-efficient-and-accurate-code).

**Comment by nalimilan** [comment]
They would certainly be useful, but I'm not aware of anybody having plans about that. Also, we're trying to move features out of StatsBase, to the Statistics stdlib module or to more specific packages, so maybe better create a new package dedicated to inequality measures (which could be loaded by StatsKit by default).

**Comment by Nosferican** [comment]
I would recommend making a Discourse post with various candidates. I think it would be quite useful. I could contribute one or two. Maybe post the link from the discourse post as a reference and close the issue?
