### ISSUE TITLE
Unweighted <: AbstractWeights

### ISSUE THREAD

**Issue by oxinabox** [JuliaStats/StatsBase.jl#516]
In a few places i've seen code that wants to support weighted and unweighted function.
where the weights input is just passed directly to a StatsBase/Statistics function,

This tends to look like:

```
function foo(x, weights)
   ...
   z = mean(x, weights)
   ...
end

function foo(x)
   ...
   z = mean(x)
   ...
end
```

where all the code is the same except that one line calling to `mean` (etc).

I thought a cleaner way to do this would be if we had an `AbstractWeights` subtype that represented unweighted.

So `mean(x, Unweighted()) = mean(x)` etc.

Then the above code could be written using default args:

```
function foo(x, weights=Unweighted())
   ...
   z = mean(x, weights)
   ...
end
```

**Comment by lbittarello** [comment]
We've been working on it!

https://github.com/JuliaStats/StatsBase.jl/pull/515
