### ISSUE TITLE
Why are non-breaking releases increasing the minor version?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/StatsBase.jl#523]
It seems that the last two releases (0.31 and 0.32) were really non breaking, right? I think in that case it is really less than ideal to increase the minor version number while we are pre 1.0, because the package manager will interpret these versions as breaking in the semver sense, which makes it cumbersome to properly take a dependency on this package.

I should say that I think everyone's life would be much easier if we just moved to 1.0.0, here and used normal semver rules for version number increases.

**Comment by davidanthoff** [comment]
> DataFrames has introduced a few subtle regressions / breaking changes on a minor release

That is how they should be doing it, right? Pre 1.0, minor releases are breaking.

> Without the ability to differentiate breaking and non-breaking API changes

But there is: for pre-1.0, a minor increase is breaking, and patch release isn't.

**Comment by rofinn** [comment]
Except that in the case of DataFrames the release wasn't intended to be breaking (i.e., with your proposed versioning it would have been a patch release), but it was, so the patch release was a useful option.

**Comment by nalimilan** [comment]
I agree with David. There's no reason to bump the minor release when we don't break anything. Maybe if we introduce significant changes that may break things even without changing API, we could bump the minor version, but we shouldn't have done so for 0.31 and 0.32 IMHO. The introduction of `eweights` isn't a serious issue as  [no package exports that name](https://pkg.julialang.org/docs/search?q=eweights).

That said, I still think that before 1.0 packages would better use `"≥ 0.32"` as the probability of breakage is relatively small (most of the API won't change) and updating all dependencies each time we make a minor release is so inconvenient that it just doesn't happen in practice.

**Comment by rofinn** [comment]
> The introduction of eweights isn't a serious issue as no package exports that name.

Except for our own internal packages... :)

**Comment by davidanthoff** [comment]
I think we should generally (across the ecosystem) not consider adding a new exported function as a breaking change. In my mind depending packages should just not blanket import exported names into their own module if they want to be protected from such a change.

**Comment by Nosferican** [comment]
The project as far as I understand it now follows the semver specification for its releases. I think this issue can be closed now.
