### ISSUE TITLE
R² generalization

### ISSUE THREAD

**Issue by getzze** [JuliaStats/StatsBase.jl#549]
For generalized models, the docs mention that `:CoxSnell` is equivalent to R² for linear models:
https://github.com/JuliaStats/StatsBase.jl/blob/0faf210f5fb84d361bd101404aadaef54376fcbd/src/statmodels.jl#L225
But, it is the likelihood ratio index (`:MacFadden`) that gives the same definition for R² for a linear model and for a Normal GLM. Indeed, `log(L)` is the sum of squares for a Normal likelihood, but `L` is a Gaussian function.
I would suggest changing this sentence to:
"The likelihood ratio index matches the classical definition of R² for linear models."

[EDIT] It is not McFadden's likelihood ratio that corresponds to the linear R², but the _deviance_ ratio. See #550.

**Comment by nalimilan** [comment]
@lbittarello You wrote this at #400. Do you remember the details?

**Comment by lbittarello** [comment]
McFadden's R² doesn't match the classical R²  because the log likelihood is equal to `0.5 * [1 + ln(2π) + σ²]`, where `σ²` is the sum of squared residuals. The constant `1 + ln(2π)` distorts the ratio `ll / ll₀`. This term cancels out in Cox and Snell's R² (which uses `exp(ll - ll₀)` instead of `ll / ll₀`).

**Comment by getzze** [comment]
Yes, McFadden uses loglikelihood and I always assumed that it was the same as the deviance. It works with the deviance ratio though, I will edit the original issue.
I created a PR to add the variant with the deviance ratio #550.

**Comment by nalimilan** [comment]
@getzze Can you update https://github.com/JuliaStats/StatsBase.jl/pull/550 to keep the mention about Cox & Snell match the classical R² then?

**Comment by nalimilan** [comment]
Closed by https://github.com/JuliaStats/StatsBase.jl/pull/550.
