### ISSUE TITLE
0.32.1 introduces a breaking change

### ISSUE THREAD

**Issue by gdkrmr** [JuliaStats/StatsBase.jl#556]
The constructor for `ZScoreTransform` changed between `v0.32.0` and `v0.32.1` and now requires an extra argument.

**Comment by Nosferican** [comment]
Could we add a deprecation method and release a `0.32.2` to fix this?

**Comment by tbeason** [comment]
I think my issue is related to this so I'll piggyback here.

```julia
x = randn(100)
standardize(ZScoreTransform,x)
```
fails on `v0.32.1`.

As a larger and only semi-related point, can we *please* just make `ZScoreTransform` be the default? I don't see why it isn't.

**Comment by kleinschmidt** [comment]
Thanks for reporting, and sorry for releasing a breaking change in a patch release.  @Nosferican, AFAICT there ARE deprecation warnings in the `fit(ZScoreTransform, ...)` which is how most users interact with it.  We could also introduce a deprecation in the constructor itself.

It also looks like the changes introduced in #490 use `dims=nothing` as a default but don't provide a constructor for that value, which is the source of @tbeason error.

Using z score as the default is unrelated, please open another issue to discuss that if there isn't one already.

**Comment by kleinschmidt** [comment]
This should be fixed once 0.32.2 is registered: https://github.com/JuliaRegistries/General/pull/10500

@tbeason, I was surprised to find that before #490, `standardize` and friends didn't work with a vector.  It now at least provides a more explicit error message (you have to specify `dims=1`)
