### ISSUE TITLE
constant normalization in autocor?

### ISSUE THREAD

**Issue by leandromartinez98** [JuliaStats/StatsBase.jl#562]
I am not sure if this is an issue or a deliberate choice. In the autocor function, the correlation is normalized by the norm of the complete vector independently of the lag. Specifically, `zz` is constant in this loop:

```
    zz = dot(z, z)
    for k = 1 : m  # foreach lag value
        r[k] = _autodot(z, lx, lags[k]) / zz
    end
```

the result is that the correlation decreases for greater lag, not because of lack of correlation, but because the size of the vectors being considered decrease relatively to the normalization. That results in a decreasing correlation even for perfectly periodical functions. 

The alternative would be to recompute `zz` for each lag, considering only the elements which will be used for the computation of the dot product.

**Comment by andreasnoack** [comment]
I think our definition deliberate and also standard. At least in the statistics literature. In Fuller's "Introduction to Statistical Time Series", he writes the autocovariance estimator as
<img width="474" alt="Screen Shot 2020-03-04 at 09 10 41" src="https://user-images.githubusercontent.com/505001/75858356-548caf00-5df8-11ea-8770-8ef0ccd78777.png">
and then the autocorrelation estimator as
<img width="397" alt="Screen Shot 2020-03-04 at 09 10 50" src="https://user-images.githubusercontent.com/505001/75858383-62dacb00-5df8-11ea-88b2-232b0f2ec5ea.png">
which is what we compute. The statistical analysis of time series is almost always asymptotic and in the limit, it doesn't matter if the variance factor consists of `n` or `n-k` terms.

I'd say that if the decrease that you mention looks significant for a problem then you are probably considering a larger lag than can be statistically justified.

**Comment by m3g** [comment]
Thank you for your feedback. Closing the issue.
