### ISSUE TITLE
'Shortcut' in fitting Histogram if binning is uniform / even

### ISSUE THREAD

**Issue by Moelf** [JuliaStats/StatsBase.jl#563]
https://github.com/JuliaStats/StatsBase.jl/blob/3762c78ba86a86671819ab8e5463a9f5e11a3988/src/hist.jl#L229-L235

if binning is even, we can do a `O(N)` edge finding, this is useful when fitting large number of events.

**Comment by Moelf** [comment]
after some fiddling I have concluded this should be done at`fit(Histogram ....)` level, for example, provide a `edges = (edge_left, edge_right), interval=` and do something like:
```
function myfit(edge::AbstractVector, closed::Symbol, x::Array{<:Real})
           diffs = diff(edge)
           diff1 = diffs[1]
           if all(isapprox.(diff1, diffs))
               bin_idxs = if closed == :right
                   @. ceil(Int, (x-edge[1]) / diff1)
               else
                   @. floor(Int, (x-edge[1]) / diff1)
               end
               weights = [count(x->x==i, bin_idxs) for i in 1:length(edge)-1]
               return edge, weights
           end
       end
```

Potentially we would have some gain:
```
julia> @benchmark Histogram(myfit(0:0.1:1, :right, $(rand(10^5)))...)
BenchmarkTools.Trial: 
  memory estimate:  786.20 KiB
  allocs estimate:  12
  --------------
  minimum time:     199.137 μs (0.00% GC)
  median time:      208.375 μs (0.00% GC)
  mean time:        220.133 μs (3.43% GC)
  maximum time:     847.417 μs (47.32% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark fit(Histogram, $(rand(10^5)), 0:0.1:1)
BenchmarkTools.Trial: 
  memory estimate:  1.53 MiB
  allocs estimate:  100003
  --------------
  minimum time:     986.340 μs (0.00% GC)
  median time:      1.042 ms (0.00% GC)
  mean time:        1.070 ms (2.29% GC)
  maximum time:     2.013 ms (35.65% GC)
  --------------
  samples:          4666
  evals/sample:     1
```

**Comment by Moelf** [comment]
bump for pointer to where to implement this since it looks like `append!` is called recursively in the current implementation

**Comment by Nosferican** [comment]
For large histogram fitting at scale it might also be good to make it work by passing the value-count pairs as well. That is probably a different approach for histogram with numerous data... currently I use the value-count pairs and run a bar plot since histogram can't handle that scale.

**Comment by Moelf** [comment]
@Nosferican huh? how did you obtain the value-count pair in the first place? also this is not only for 1D but also higher dimension.

**Comment by Nosferican** [comment]
Something like `countmap` would be the most straightforward.

**Comment by Moelf** [comment]
won't work if I have continuous data.

**Comment by Nosferican** [comment]
Aye. For continuous data you need to `cut`/`bin` of some kind which depends on the algorithm used.

**Comment by Moelf** [comment]
update:
it seems that the cause for the slowness is `_edge_binindex` thus the searchsorted, compare the following:
1.
```
function fit(::Type{Histogram{T}}, v::AbstractVector, edg::AbstractVector; closed::Symbol=:left) where {T}
    diffs = diff(edg)
    diff1 = diffs[1]
    weights = zeros(length(edg)-1)
    _edg = if all(isapprox.(diff1, diffs))
        edg[begin]:diff1:edg[end]
    else
        edg
    end
    if closed == :right
        for x in v
            weights[ceil(Int, (x-edg[1]) / diff1)] += 1
        end
    else
        for x in v
            weights[floor(Int, (x-edg[1]) / diff1) + 1] += 1
        end
    end
    Histogram(edg, weights, closed)
end
```
```
julia> @btime fit(Histogram, $(rand(10^6)), 0:0.1:1)
  2.162 ms (5 allocations: 528 bytes)
```

if we replace the `ceil(Int, (x-edg[1]) / diff1)` by one of the following:
```
            # weights[searchsortedfirst(_edg, x) - 1 ] += 1
            # weights[_edge_binindex(_edg, closed, x)] += 1
```
we immediately get slow down
```
julia> @btime fit(Histogram, $(rand(10^6)), 0:0.1:1)
  28.270 ms (5 allocations: 528 bytes)
```

**Comment by Moelf** [comment]
basically it comes down to we shouldn't use base search sorted:
```
julia> @btime searchsortedfirst(0.2:0.5:30, 12, Base.Order.ForwardOrdering())
  120.920 ns (0 allocations: 0 bytes)
25

julia> @btime ceil(Int, (12-0.2) / 0.5)
  0.020 ns (0 allocations: 0 bytes)
24
```

**Comment by mschauer** [comment]
I’d rather say let’s check if search sorted could be made faster here

**Comment by oschulz** [comment]
> @moelf if binning is even, we can do a O(N) edge finding, this is useful when fitting large number of events.

We could, of course, add a method `_edge_binindex(edge::AbstractRange, closed::Symbol, x::Real)`. But _edge_binindex should already run in O(1) for AbstractRange because `searchsortedfirst` and similar are already specialized for `AbstractRange`

```julia
function searchsortedfirst(a::AbstractRange{<:Real}, x::Real, o::DirectOrdering)::keytype(a)
    require_one_based_indexing(a)
    if step(a) == 0
        lt(o, first(a), x) ? length(a) + 1 : 1
    else
        n = round(Integer, clamp((x - first(a)) / step(a) + 1, 1, length(a)))
        lt(o, a[n] ,x) ? n + 1 : n
    end
end
```

**Comment by oschulz** [comment]
I wonder why searchsortedfirst takes so long, though - but it should run in constant time.

**Comment by Moelf** [comment]
https://github.com/JuliaStats/StatsBase.jl/pull/613#issuecomment-907618429
