### ISSUE TITLE
Interquartile Range - manual computation vs iqr function

### ISSUE THREAD

**Issue by ksangabriel** [JuliaStats/StatsBase.jl#572]
Hi Team,

I was trying out the iqr() but the value it returns is wrong, I think.

```
# Sorted
samples = 98, 90, 70, 18, 92, 92, 55, 83, 45, 95, 88, 76, 100

# I IQR value of 22.0
println(iqr(samples))
```
When manually computing for IQR, I get `31.0`.

I used this [online calculator](https://www.statisticshowto.datasciencecentral.com/calculators/interquartile-range-calculator/) to compute for IQR, it shows `31.0`.

I tried these too:

- https://goodcalculators.com/interquartile-range-calculator/

- https://mathcracker.com/interquartile-range-calcul

**Comment by nalimilan** [comment]
There are many definitions of quantiles, which vary slightly in cases where the quartile falls between two observations. See https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample. The calculators you used probably take a different definition. We use the same definition as R, so you can check against these if you have doubts, but I'm pretty confident we match their results.
