### ISSUE TITLE
`countmap` should accept any iterator

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/StatsBase.jl#581]
```
julia> x = [1, 2, 3]
3-element Array{Int64,1}:
 1
 2
 3

julia> countmap(skipmissing(x))
ERROR: MethodError: no method matching countmap(::Base.SkipMissing{Array{Int64,1}})
```

**Comment by xiaodaigh** [comment]
> countmap(skipmissing(x))

`countmap(itr) = countmap(collect(itr))` should suffice although not efficient memory wise.

**Comment by nalimilan** [comment]
Actually `addcounts!` doesn't rely on indexing at all, so all what's needed is to remove the `::AbstractArray` requirement in the signature (and add tests). The weighted method will require a few adjustments, but it should be quite easy too.

**Comment by alanedelman** [comment]
I could really use this.
