### ISSUE TITLE
RFC: GPU cuda-based countmap

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaStats/StatsBase.jl#585]
I have implemented [a CUDA.jl based `countmap`](https://github.com/xiaodaigh/CuCountMap.jl) that is faster than existing `countmap` by 5x using GPU (even after factoring the costs of transfer from CPU to GPU and back again). 

I wish to contribute back to here. But there is a dilemma which is that `CUDA.jl` is a large dependency and not everyone wants to use GPUs. So ideally, I would make the dependency use Require.jl.

Would that be a good approach?

I would need to intro a new algorithm called `:gpu_hist` in addition to `:auto, :dict, :radixsort`.

I am also happy to keep my GPU `countmap` in a separate package too.

**Comment by nalimilan** [comment]
Unfortunately I don't think we can add a dependency on CUDA, especially if we want to move this code to the Statistics stdlib. Maybe you can use `countmap(x, GPUHist())` or something in your package?
