### ISSUE TITLE
Can we put some example on sample methods?

### ISSUE THREAD

**Issue by DataPsycho** [JuliaStats/StatsBase.jl#610]
Hi,
The doc string does not provide any concrete exmaple that how to use[ the sample method ](https://github.com/JuliaStats/StatsBase.jl/blob/08d4b77a4b42ef8cadb67b98da65e7fbd9959e0b/src/sampling.jl#L379) .
Can we put some example on that in the doc string.

Such as: 
```
julia> [sample(["High", "Medium", "Low"], pweights([0.25,0.45,0.30])) for i=1:5]
5-element Array{String,1}:
 "Low"
 "Medium"
 "Medium"
 "Medium"
 "Medium"
```

and explain the parameters.

The `help?>` does not provide any concrete example on that.

**Comment by nalimilan** [comment]
Sure. Feel free to make a pull request. But maybe the array comprehension doesn't need to be shown?

**Comment by DataPsycho** [comment]
Ok. Will do a pull and also will remove the list comprehension. Thanks
