### ISSUE TITLE
ERROR: ArgumentError: no default `Tables.columns` implementation for type: StatsBase.CoefTable

### ISSUE THREAD

**Issue by christophergandrud** [JuliaStats/StatsBase.jl#654]
The `StatsBase.CoefTable` [documentation](https://juliastats.org/StatsBase.jl/latest/statmodels/#StatsBase.coeftable) mentions that:

> The returned `CoefTable` object implements the Tables.jl interface, and can be converted e.g. to a DataFrame via `using DataFrames; DataFrame(coeftable(model))`. 

However, when I try this with a `CoefTable` from GLM I get the following error: 

```julia
ERROR: ArgumentError: no default `Tables.columns` implementation for type: StatsBase.CoefTable
```

Here is a minimal reproducible example:

```julia
using GLM, DataFrames, StatsBase

data = DataFrame(X=[1,2,3], Y=[2,4,7])

ols = lm(@formula(Y ~ X), data)

DataFrame(coeftable(ols))
```

**Comment by nalimilan** [comment]
You're looking at the documentation for the development version. This hasn't been released yet.

**Comment by christophergandrud** [comment]
Thanks for the clarification. Really looking forward to this feature!

**Comment by nalimilan** [comment]
Let's release it then: https://github.com/JuliaStats/StatsBase.jl/pull/655
