### ISSUE TITLE
Possible error in autocov?

### ISSUE THREAD

**Issue by bgctw** [JuliaStats/StatsBase.jl#665]
In thinking how to compute the autocorrelation of a series with missings, I wondered whether the code of autocov is correct. To my understanding of the source code, the code estimates the `E[(x1-mean(x1))(x2-mean(x2))]` by using the dot function and afterwards dividing by `lx = length(x)`, which is the length of the original series. However, to my understanding for lag k, the two vectors x1 and x2 being correlated are subsets of the original series of only length `lx -k`.

Hence, I think lines 73 and 90 in signalcorr.jl should be changed to
`r[k] = _autodot(z, lx, lags[k]) / (lx -k)`

What am I missing?

**Comment by andreasnoack** [comment]
Please see https://github.com/JuliaStats/StatsBase.jl/issues/273
