### ISSUE TITLE
Register a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaStats/StatsBase.jl#711]
On Julia nightly, tests pass on `StatsBase#master` but fail on `StatsBase@0.33.9`. (IIUC, the tests were fixed by #707.)

It would be great to get a new release, so that downstream users that run the StatsBase test suite (for example, PkgEval) can take advantage of the fixed tests.

cc: @nalimilan @bkamins @ararslan @timholy

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/43743
