### ISSUE TITLE
dims keyword arg for `mad` ?

### ISSUE THREAD

**Issue by bjarthur** [JuliaStats/StatsBase.jl#724]
is there a reason not to have it so that the interfaces matches median, mean, std, etc. ?

**Comment by andreasnoack** [comment]
I don't think so. I think it's partly because nobody has done the work and partly because there has been a slight trend towards using higher or functions like `mapslices` instead of adding more keywords.

**Comment by bjarthur** [comment]
IIRC `mapslices` used to be slow.  was that the case, and if so, is it still?

**Comment by nalimilan** [comment]
`mapslices` is slow as it makes copies, and it can't change until Julia 2.0. But `eachslice` can be used instead.

**Comment by nalimilan** [comment]
I think `sem.(eachrow(x))`, `sem.(eachcol(x))` and  `sem.(eachslice(x, ...))` are the way to go now. Arguments probably won't be added because these syntaxes are short and explicit.
