### ISSUE TITLE
Feature request: Running Stats?

### ISSUE THREAD

**Issue by NAThompson** [JuliaStats/StatsBase.jl#729]
Forgive me if this is a dup, but I checked the docs, issues and PRs, but didn't see any documentation on running statistics. Near as I can tell, we need to have an array on hand in order to compute mean and standard deviation, but [online algorithms](https://www.johndcook.com/blog/standard_deviation/) exist so that we can consume samples as they arrive.

Is this an interesting feature for this repo?

**Comment by wildart** [comment]
Take a look https://github.com/joshday/OnlineStats.jl

**Comment by nalimilan** [comment]
Closing as OnlineStats is the package to use.
