### ISSUE TITLE
Let var, std, cor take a CovarianceEstimator

### ISSUE THREAD

**Issue by tpgillam** [JuliaStats/StatsBase.jl#734]
Currently `StatsBase.jl` defines `CovarianceEstimator` [here](https://github.com/JuliaStats/StatsBase.jl/blob/179c533f8ea8c573bac295d04cdbb66f4d3bf9c4/src/cov.jl#L158), and defines methods of `cov` that take one as the first argument.

I think it would be convenient to allow similar dispatches for related methods. These could have fairly simple default implementations, something like the following (untested) sketch:

```julia
var(ce::CovarianceEstimator, x::AbstractVector; kwargs...) = cov(ce, x; kwargs...)

std(ce::CovarianceEstimator, args...; kwargs...) = sqrt(var(ce, args...; kwargs...))

cov2cor!(x::AbstractMatrix) = cov2cor!(x, sqrt.(diag(x)))

cor(ce::CovarianceEstimator, x::AbstractVector, y::AbstractVector) = cov2cor!(cov(ce, x, y))
cor(ce::CovarianceEstimator, X::AbstractMatrix; kwargs...) = cov2cor!(cov(ce, X; kwargs...))
cor(ce::CovarianceEstimator, X::AbstractMatrix, w::AbstractWeights; kwargs...) = cov2cor!(cov(ce, X, w; kwargs...))
```

Any thoughts or objections to this? I'm happy to make a PR for more concrete discussion if this seems reasonable :)

**Comment by nalimilan** [comment]
Why not, but I guess you'd also expect CovarianceEstimation.jl (or another package) to define the corresponding functions? Otherwise it wouldn't be super useful.

@mateuszbaran Any opinion?

**Comment by tpgillam** [comment]
I’d propose including something like the default implementations above in StatsBase. 

At that point, so long as the first dispatch of `cov` is available (since that is effectively `var`), it might not generally be necessary to override for specific estimators, I would hope?

**Comment by nalimilan** [comment]
Ah, got it. Yes, makes sense. Let's hear what @mateuszbaran says though.

**Comment by mateuszbaran** [comment]
I think this definitely makes sense for `cor` but so far I haven't seen the need for fancy methods of estimating variance and standard deviation.

**Comment by tpgillam** [comment]
>  the need for fancy methods of estimating variance and standard deviation.
For example, my current case would be https://github.com/mateuszbaran/CovarianceEstimation.jl/issues/80 - specifically, I would like to provide equivalent functions for [biweight_midvariance](https://docs.astropy.org/en/stable/api/astropy.stats.biweight_midvariance.html) and biweight_scale](https://docs.astropy.org/en/stable/api/astropy.stats.biweight.biweight_scale.html). 

To me, it seems nice to just implement a `Biweight` (or similar name) covariance estimator, and then be able to get these things with `var(Biweight(), ...)` and `std(Biweight(), ...)`.

[I would be surprised if there aren't other regularisation techniques that would also fit this pattern - winsorising might be one off the top of my head]

**Comment by mateuszbaran** [comment]
Sure, if you have a use for that, don't mind my comment :slightly_smiling_face:

**Comment by nalimilan** [comment]
OK feel free to make a PR @tpgillam then.
