### ISSUE TITLE
covariance and correlation

### ISSUE THREAD

**Issue by rodinalex** [JuliaStats/StatsBase.jl#739]
There appears to be an issue in the autocovariance and autocorrelation functions. After taking the dot product of the two vectors, the result is divided by the length of the total vector lx. Shouldn't the division be by (lx - lag) to correspond to the number of terms in the dot-sum since we are looking for the mean of the sum?

**Comment by andreasnoack** [comment]
Dup of https://github.com/JuliaStats/StatsBase.jl/issues/562
