### ISSUE TITLE
quantile() incompatible with CUDA/CuArrays

### ISSUE THREAD

**Issue by drayer587** [JuliaStats/StatsBase.jl#740]
Not sure if this is within scope, but it seems just about everything else in Base (LinearAlgebra, Statistics, ...) slides into CuArrays just fine.

The problem is the internal `_quantilesort!` checks:

```
ismissing(v[end]) && throw(ArgumentError("quantiles are undefined in presence of missing values"))
isnan(v[end]) && throw(ArgumentError("quantiles are undefined in presence of NaNs"))
```

which will throw the scalar indexing error because `[end]` isn't allowed with CuArrays.

Solutions that come to mind include either a map of `ismissing()` and `isnan()` (slower and probably not ideal) or another check like `sorted` here to bypass these checks if set to be true, e.g. a default of `allvalid::Bool=false`

Example:

```
julia> typeof(ustrip.(dists_vec))
CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}

julia> size(ustrip.(dists_vec))
(499500,)

julia> quantile(sort(ustrip.(dists_vec)),[0.25,0.75],sorted=true)
ERROR: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] assertscalar(op::String)
   @ GPUArrays ~/.julia/packages/GPUArrays/3sW6s/src/host/indexing.jl:53
 [3] getindex
   @ ~/.julia/packages/GPUArrays/3sW6s/src/host/indexing.jl:86 [inlined]
 [4] _quantilesort!(v::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, sorted::Bool, minp::Float64, maxp::Float64)
   @ Statistics /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Statistics/src/Statistics.jl:959
 [5] #quantile!#49
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Statistics/src/Statistics.jl:938 [inlined]
 [6] quantile(v::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, p::Vector{Float64}; sorted::Bool, alpha::Float64, beta::Float64)
   @ Statistics /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Statistics/src/Statistics.jl:1052
 [7] top-level scope
   @ REPL[105]:1
 [8] top-level scope
   @ ~/.julia/packages/CUDA/YpW0k/src/initialization.jl:52
```

**Comment by nalimilan** [comment]
This code live in Statistics, not in StatsBase:
https://github.com/JuliaLang/Statistics.jl/blob/2048f5b369913e168016e3ca272086b6742388be/src/Statistics.jl#L978

I guess a possible trick would be to run `any(x -> ismissing(x) || (x isa Number && isnan(x), @view x[end:end])`? But that's really ugly. I'd find it annoying to make code more complex just because CUDA throws an error for an operation that actually works with `CuArrays.allowscalar(true)`. Clearly here this check is extremely cheap and we can't make it faster.

We could also add an argument as you propose, but that would only be useful for CUDA so why not use `@allowscalar` like the error message suggests?

**Comment by drayer587** [comment]
You're right; this is the wrong place. Still learning here; will probably just post this in CUDA.jl which should just define it's own `quantile()` and necessary `_quantilesort!()`

I'd delete this issue if I could, ha.
