### ISSUE TITLE
Add `rms` (root-mean-square) function

### ISSUE THREAD

**Issue by acxz** [JuliaStats/StatsBase.jl#761]
I think it would be a good idea to have a `rms` function in stats.

If this is a feature that would be welcome, I'd love to try my hand at contributing this.

**Comment by rikhuijzer** [comment]
There are a whole lot of measures already available in pure Julia via [MLJBase.jl](https://github.com/JuliaAI/MLJBase.jl/). Docs are at <https://alan-turing-institute.github.io/MLJ.jl/v0.3/measures/> and source at <https://github.com/JuliaAI/MLJBase.jl/tree/dev/src/measures>:

```julia
julia> using MLJBase

julia> rms(1:3, 2:4)
1.0
```

**Comment by nalimilan** [comment]
Isn't `rmsd` what you're looking for? https://juliastats.org/StatsBase.jl/latest/deviation/#StatsBase.rmsd

**Comment by acxz** [comment]
`rmsd` is exactly what I'm looking for. I tried searching just `rms` and didn't get any hits from the github search I apologize, shouldve looked deeper into the docs. Thanks @nalimilan !
