### ISSUE TITLE
Documentation mistake?: implementation of `varcorrection` is different from the comment in weights.jl

### ISSUE THREAD

**Issue by phasetr** [JuliaStats/StatsBase.jl#784]
The problem is [here](https://github.com/JuliaStats/StatsBase.jl/blob/e8ab26500d9a34ef358b2d3cf619ae41c71785fc/src/weights.jl#L348-L356). 

```
"""
    varcorrection(w::UnitWeights, corrected=false)
* `corrected=true`: ``\\frac{n}{n - 1}``, where ``n`` is the length of the weight vector
* `corrected=false`: ``\\frac{1}{n}``, where ``n`` is the length of the weight vector
This definition is equivalent to the correction applied to unweighted data.
"""
@inline function varcorrection(w::UnitWeights, corrected::Bool=false)
    corrected ? (1 / (w.len - 1)) : (1 / w.len)
```

The comment say that we get `\frac{n}{n - 1}` if `corrected=true`, but the implementation is `(1 / (w.len - 1))`. Which is true? Implementation is right, I think.

**Comment by nalimilan** [comment]
The docstring says "where ``n`` is the length of the weight vector", so these are the same, right? This docstring only applies to `UnitWeights`.

**Comment by phasetr** [comment]
The number `n` is `w.len`, I think.

**Comment by phasetr** [comment]
Thank you for your quick responce! I close this issue.
