### ISSUE TITLE
weighted kurtosis

### ISSUE THREAD

**Issue by JakeZw** [JuliaStats/StatsBase.jl#788]
In some previous testing I found `sum()` to be slower than a for loop.  Thus I suspect that the function 

`function kurtosis(v::RealArray, wv::AbstractWeights, m::Real)`

could be speeded up by replacing the sum with 
```julia
sw = 0.0

for ....
    sw += w_i    # add this line to the existing for loop
end

sw = sum(wv)    # remove this line
```

**Comment by nalimilan** [comment]
`sum(::AbstractWeights)` is just a accessor for the `w.sum` field, so it's basically free (the sum is computed when constructed `AbstractWeights`. Also, `sum` is more accurate than a plain loop of additions as it uses pairwise summation. It's a bit slower but normally the overhead should be limited.
