### ISSUE TITLE
New patch version

### ISSUE THREAD

**Issue by t-bltg** [JuliaStats/StatsBase.jl#803]
Hi,

Would it be possible to tag a new patch release for 43880cf37cc2b034a3e3d9aa34a255e34d648e21 (https://github.com/JuliaStats/StatsBase.jl/pull/792), in order to avoid [nightly failures](https://github.com/JuliaPlots/UnicodePlots.jl/runs/6949508348?check_suite_focus=true) ?

Thanks.

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/62797

**Comment by t-bltg** [comment]
Awesome, thanks !
