### ISSUE TITLE
`countmap` weird behaviour for -0.0

### ISSUE THREAD

**Issue by jhbdiehl** [JuliaStats/StatsBase.jl#809]
```julia
t = [0., -0.]
ct = countmap(t, [1 for e in t])
```

will output:
```julia
Dict{Float64, Int64} with 2 entries:
  0.0  => 1
  -0.0 => 1
```

Changing t to Integers
```julia
t = [0, -0]
ct = countmap(t, [1 for e in t])
```
or removing the weights
```julia
t = [0., -0.]
ct = countmap(t)
```

leads to the expected behaviour:
```julia
Dict{Float64, Int64} with 1 entry:
  0.0 => 2
```

Now all of this does not seem problematic until you start changing the keys, e.g.
```julia
Dict(keys(ct) .+ 1 .=> values(ct))
```

leads to
```julia
Dict{Float64, Int64} with 1 entry:
  1.0 => 1
```
in the first case, instead of 
```julia
Dict{Float64, Int64} with 1 entry:
  1.0 => 2
```

Therefore I think this is not the intended behaviour.
To be fair this could also be interpreted as a bug in the general Dict routine.

**Comment by nalimilan** [comment]
Good catch. See https://github.com/JuliaStats/StatsBase.jl/pull/831. This may end up going in the opposite direction you expected though.

Note that the different behavior of `t = [0, -0]` isn't a bug in StatsBase, it's just that `-0` it exactly the same as `0`, as the equivalent of `-0.0` doesn't exist for `Int`. In other words, the information is lost even before `countmap` has the chance to see it.

Likewise, `Dict(keys(ct) .+ 1 .=> values(ct))` simply retains the value for the last time the key was seen in `(keys(ct) .+ 1 .=> values(ct)) == [1.0 => 1, 1.0 => 1]`, it doesn't sum counts (as the `Dict` constructor isn't made to work only with counts but with any kind of data).
