### ISSUE TITLE
0.33.18 broken build

### ISSUE THREAD

**Issue by spcogg** [JuliaStats/StatsBase.jl#811]
Hey team, I'm getting a broken build for the latest release of 0.33.18 - can someone confirm if this is a general issue, or just me?

![image](https://user-images.githubusercontent.com/8016236/178261210-7587d591-df3c-4852-b8cf-7be4f330f93e.png)

Reverting to an older version (in this case i've tried 0.33.17 and 0.33.14) works for me.

**Comment by nalimilan** [comment]
Sorry for the delay. I don't see this locally, and tests run fine on CI. Have you tried in a clean package environment?

**Comment by spcogg** [comment]
All good and thanks for getting around to this.
I'm now not able to repro this either on my local, and the latest 0.33.21 works fine on my machine so i'll close this. Guessing if no one else has reported this then it must be just me.
