### ISSUE TITLE
Unused variable, `totwidth` in statmodels.jl

### ISSUE THREAD

**Issue by phasetr** [JuliaStats/StatsBase.jl#822]
In `statmodels.jl`, [L169](https://github.com/JuliaStats/StatsBase.jl/blob/master/src/statmodels.jl#L169), we have a variable `totwidth`, but this is unused in the function `show`.

**Comment by nalimilan** [comment]
Thanks for spotting this. See https://github.com/JuliaStats/StatsBase.jl/pull/830.
