### ISSUE TITLE
How to get critical value with native  julia code?

### ISSUE THREAD

**Issue by phpsmarter** [JuliaStats/StatsBase.jl#828]
Can not find native  method to get  critical value of t-test 

At now just use R language function 

```julia
  function get_criticalvalue(df,alpha=0.05)
       @rput df alpha
        R"""
	    res<-qt(p=alpha/2, df=df, lower.tail=FALSE)
        """
        return @rget  res
  end
```

**Comment by ararslan** [comment]
Hi @phpsmarter, please direct usage questions to [the Julia Discourse](https://discourse.julialang.org); we use the issue tracker for bug reports and feature requests.

In this case, note the R function you're calling: `qt`, which retrieves quantiles from the t-distribution. In Julia, distributions are provided by the [Distributions](https://github.com/JuliaStats/Distributions.jl) package, which extends `quantile` from [Statistics](https://github.com/JuliaStats/Statistics.jl) to provide this functionality.
