### ISSUE TITLE
Define method fit! akin to predict!

### ISSUE THREAD

**Issue by svs14** [JuliaStats/StatsBase.jl#83]
Method `fit` is defined but no `fit!`: https://github.com/JuliaStats/StatsBase.jl/blob/master/src/statmodels.jl#L13

Is it possible to have this defined alike to `predict` and `predict!`?

**Comment by Rory-Finnegan** [comment]
I'd also like this to be defined for the same reason @simonster mentioned.  I'm often defining a `fit!` in my own code anyways.

**Comment by simonster** [comment]
Added in 54bdb20674b4b2e82f25ce53cbc062db29cbeafc
