### ISSUE TITLE
tiedrank does not support dims

### ISSUE THREAD

**Issue by behinger** [JuliaStats/StatsBase.jl#848]
MWE
```julia
tiedrank(rand(10,10),dims=2)
```
Results in
```julia
MethodError: no method matching sortperm(::Vector{Float64}; dims=2)
```
something like this works
```
mapslices(tiedrank,rand(10,10),dims=2)
```
but the documentation of tiedrank states: `Supports the same keyword arguments as the sort function.` which made me believe, `dims` should work. Bug or documentation wrong?

Ultimatively, I am trying to estimate ranks of ragged/sparse matrices columns as fast as possible.

**Comment by behinger** [comment]
while looking for an inplace operator on tiedrank, I stumbled upon this:
https://github.com/JuliaLang/julia/pull/45211

it seems sortperm will get a dims in julia 1.9

**Comment by ParadaCarleton** [comment]
`eachslice` should work as of Julia 1.9 (best to avoid `dims` keywords from now on).
