### ISSUE TITLE
What is breaking from 0.33 to 0.34

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/StatsBase.jl#862]
hi there,

it would be great if you guys can edit this: https://github.com/JuliaStats/StatsBase.jl/releases/tag/v0.34.0 and add what is breaking (and hence requiring the version bump). Would make the life of many downstream developers easier as we are currently facing CompatHelper PRs but hard to judge whether we should act or just merge.

**Comment by andreasnoack** [comment]
It's #840. Generally, I'd merge a CompatHelper PR if your test suite passes.

**Comment by Datseris** [comment]
Thanks! Generally, I do this, but it also can fall victim of tests passing simply because there wasn't a test that would catch this breaking change, so I always like to look up the changelogs for breaking stuff.

**Comment by ararslan** [comment]
> it would be great if you guys can edit this: https://github.com/JuliaStats/StatsBase.jl/releases/tag/v0.34.0 and add what is breaking (and hence requiring the version bump)

Done, thanks for the suggestion!
