### ISSUE TITLE
unused z array in entropy

### ISSUE THREAD

**Issue by feanor12** [JuliaStats/StatsBase.jl#938]
https://github.com/JuliaStats/StatsBase.jl/blob/88b481809cf3a4b4e381be37f4372122c2d7c361/src/scalarstats.jl#L429-L439

**Comment by devmotion** [comment]
`z` here is not an array but a zero value of the same type as the elements in the array `p`.

**Comment by feanor12** [comment]
I think I understand it now. Thank you!
