### ISSUE TITLE
norepeat function in StatsBase/src/misc.jl

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/StatsBase.jl#95]
I don't see that this function is used anywhere, so it could probably be deleted.  In case it is used it should be rewritten as

norepeat(a::AbstractArray) = length(Set(a)) == length(a)

there is no need to sort the array to determine whether or not there are repeats.

**Comment by ararslan** [comment]
I realize this is an old issue but two things now are apparent: `norepeat` isn't exported from this package, and Base now has an equivalent function, `allunique`, so even if it was exported it would be unnecessary.

**Comment by nalimilan** [comment]
Thanks for noticing it!
